"use client";
import {useEffect,useMemo,useState} from 'react';
import AppLayout from '../../components/AppLayout';
import {api,BASE} from '../../lib/api';
import {BookOpen,CheckCircle2,ExternalLink,PlayCircle,FileText,Bookmark,Presentation,Play,Search} from 'lucide-react';
type Subject={id:string;slug?:string;name:string;overview?:string;description?:string};
type Resource={id:string;title:string;url:string;kind:string;level?:string;provider?:string;competency?:string;why?:string};
const kinds=['all','documentation','youtube','pdf','slides','course','reference','learning'];
function youtubeId(url:string){const m=url.match(/[?&]v=([^&]+)/)||url.match(/youtu\.be\/([^?]+)/);return m?.[1]||''}
export default function Learn(){const[subjects,setSubjects]=useState<Subject[]>([]),[resources,setResources]=useState<Resource[]>([]),[progress,setProgress]=useState<Record<string,any>>({}),[q,setQ]=useState(''),[kind,setKind]=useState('all'),[subject,setSubject]=useState('all'),[loading,setLoading]=useState(true),[materialCount,setMaterialCount]=useState(0);
 useEffect(()=>{Promise.all([api<any>('/api/v1/subjects'),api<any>('/api/v1/resources'),api<any>('/api/v1/materials'),api<any>('/api/v1/learning/progress')]).then(([s,r,m,p])=>{setSubjects(s.items||[]);setResources(r.items||[]);setMaterialCount((m.items||[]).length);setProgress(p.items||{})}).catch(()=>{}).catch(()=>{}).finally(()=>setLoading(false))},[]);
 async function mark(r:Resource,status:string){await api('/api/v1/learning/progress',{method:'POST',body:JSON.stringify({resource_id:r.id,status,competency:r.competency||r.title})});setProgress(x=>({...x,[r.id]:{status}}))}
 const filtered=useMemo(()=>resources.filter(r=>`${r.title} ${r.kind} ${r.level||''} ${r.competency||''} ${r.why||''}`.toLowerCase().includes(q.toLowerCase())&&(kind==='all'||r.kind.toLowerCase()===kind)&&(subject==='all'||r.competency===subject)),[resources,q,kind,subject]);
 const videos=filtered.filter(r=>r.kind==='youtube'&&youtubeId(r.url)).slice(0,3);
 return <AppLayout><div className="page"><div className="page-head"><div><div className="eyebrow">Learning hub</div><h1>Learn what closes the gap.</h1><p>Courses, YouTube lessons, references, PDFs and presentation resources mapped to the fields in the supplied Developer + AI Engineer roadmap.</p></div></div>
 {loading?<div className="empty">Loading learning catalog…</div>:<><section className="panel"><div className="panel-head"><div><div className="eyebrow">Subjects</div><h2>Core competency areas</h2><p className="muted">The library is automatically scanned from the project <b>learning-materials</b> folder. Add YouTube links to a subject <b>links.txt</b>, or drop PDFs/PPTs/PPTXs into its <b>materials</b> folder.</p></div><div className="tag blue">{materialCount} folder materials live</div><BookOpen/></div><div className="grid grid-4">{subjects.map(s=><article className="signal" key={s.id}><b>{s.name}</b><span>{s.overview||s.description||'Structured subject path'}</span></article>)}</div></section>
 <section className="panel" id="resources" style={{marginTop:16}}><div className="panel-head"><div><div className="eyebrow">Resource library</div><h2>Links, videos, PDFs & slides</h2></div><div className="action-row"><label className="field" style={{minWidth:220}}><span>FIELD</span><select value={subject} onChange={e=>setSubject(e.target.value)}><option value="all">All fields</option>{subjects.map(s=><option key={s.id} value={s.name}>{s.name}</option>)}</select></label><Search size={15}/><input style={{maxWidth:240}} value={q} onChange={e=>setQ(e.target.value)} placeholder="SEARCH RESOURCES…" aria-label="Search resources"/></div></div>
 <div className="interview-types" style={{marginBottom:14}}>{kinds.map(k=><button className={kind===k?'active':''} key={k} onClick={()=>setKind(k)}>{k==='all'?'ALL':k.toUpperCase()}</button>)}</div>
 {filtered.length?<div className="resource-grid">{filtered.map(r=>{const done=progress[r.id]?.status==='completed';const icon=r.kind==='youtube'?<Play size={12}/>:r.kind==='pdf'?<FileText size={12}/>:r.kind==='slides'?<Presentation size={12}/>:<ExternalLink size={12}/>;const href=r.url.startsWith('/api/')?`${BASE}${r.url}`:r.url;return <article className="resource" key={r.id}><span className="tag blue resource-kind">{(r.kind||'resource').toUpperCase()}{r.level?` · ${r.level}`:''}</span><h3>{r.title}</h3><p>{r.why||r.competency||r.provider||'SKILLSETRA catalog resource'}</p><div className="action-row"><a href={href} target="_blank" rel="noreferrer" download={r.kind==='pdf'||r.kind==='slides'?true:undefined}>{icon} Open</a><button className="button" onClick={()=>mark(r,done?'in_progress':'completed')}>{done?<CheckCircle2 size={12}/>:<PlayCircle size={12}/>} {done?'Completed':'Mark complete'}</button><button className="button" onClick={()=>mark(r,progress[r.id]?.status==='bookmarked'?'unbookmarked':'bookmarked')}><Bookmark size={12}/> {progress[r.id]?.status==='bookmarked'?'Saved':'Save'}</button></div></article>})}</div>:<div className="empty">No resources match this filter.</div>}</section>
 {videos.length>0&&<section className="panel" style={{marginTop:16}}><div className="panel-head"><div><div className="eyebrow">Watch inside SKILLSETRA</div><h2>Recommended YouTube lessons</h2></div><PlayCircle/></div><div className="grid grid-3">{videos.map(v=><article className="resource" key={v.id}><iframe title={v.title} src={`https://www.youtube-nocookie.com/embed/${youtubeId(v.url)}`} style={{width:'100%',aspectRatio:'16/9',border:0,borderRadius:10}} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen/><h3 style={{marginTop:10}}>{v.title}</h3><a href={v.url} target="_blank" rel="noreferrer">Open on YouTube <ExternalLink size={12}/></a></article>)}</div></section>}
 <section className="panel" style={{marginTop:16}}><div className="panel-head"><div><div className="eyebrow">Folder-powered library</div><h2>Drop material into the project — it appears here automatically</h2><p className="muted">Edit the subject text files or add PDFs/PPTs/PPTXs. The backend scans the folder at request time.</p></div><FileText/></div><div className="grid grid-3"><article className="signal"><b>YouTube / web links</b><span>Edit <code>learning-materials/&lt;subject&gt;/links.txt</code>. One line per resource.</span></article><article className="signal"><b>PDF / PPT / PPTX</b><span>Place files inside that subject's <code>materials/</code> folder.</span></article><article className="signal"><b>Automatic mapping</b><span>The folder name becomes the subject/competency and resources appear in Learning.</span></article></div></section>
<section className="panel" style={{marginTop:16}}><div className="panel-head"><div><div className="eyebrow">PPTX study decks</div><h2>Downloadable presentation resources</h2></div><Presentation/></div><div className="resource-grid">{[{id:'ai-engineering',title:'AI Engineering Study Deck'},{id:'system-design',title:'System Design Interview Deck'},{id:'interview-prep',title:'Technical Interview Prep Deck'}].map(d=><article className="resource" key={d.id}><Presentation size={22}/><h3>{d.title}</h3><p>Offline-friendly SKILLSETRA study deck with prompts for evidence and practice.</p><a href={`/decks/${d.id}.pptx`} download>Download PPTX <ExternalLink size={12}/></a></article>)}</div></section>
 <section className="panel" style={{marginTop:16}}><div className="panel-head"><h2>Bundled field guides</h2><FileText/></div><div className="resource-grid">{['ai-engineering','backend-development','data-science','frontend-development','ml-engineering','cybersecurity'].map(x=><article className="resource" key={x}><h3>{x.replaceAll('-',' ')}</h3><a href={`/field-guides/${x}-field-guide.pdf`} target="_blank" rel="noreferrer">Open local PDF <FileText size={12}/></a></article>)}</div></section></>}</div></AppLayout>}
