"use client";
import {useState} from "react";
import AppLayout from "../../components/AppLayout";
import AIControls from "../../components/AIControls";
import {api} from "../../lib/api";
import {runPuter} from "../../lib/ai";
import {Brain,ArrowRight,RotateCcw,Copy,Check} from "lucide-react";
function blocks(text:string){const labels=["ASSUMPTIONS","CAUSAL CHAIN","OBSERVED EVIDENCE","ALTERNATIVES","TRADE-OFFS","RISKS","MISSING EVIDENCE","VERIFICATION STEPS"];const out:any[]=[];let current:any=null;for(const line of text.split(/\r?\n/)){const clean=line.trim();const label=labels.find(x=>clean.toUpperCase().startsWith(x));if(label){current={label,text:""};out.push(current);const rest=clean.slice(label.length).replace(/^[:\-\s]+/,"");if(rest)current.text=rest}else if(current){current.text+=(current.text?"\n":"")+clean}}return out.length?out:[{label:"AI ANALYSIS",text}];}
export default function Reasoning(){const [problem,setProblem]=useState("A production API becomes slow only when traffic spikes. CPU is moderate, database connections are near their limit, and retry traffic increases during timeouts. Explain the most likely causal chain and how you would verify it.");const [answer,setAnswer]=useState("");const [analysis,setAnalysis]=useState("");const [busy,setBusy]=useState(false);const [provider,setProvider]=useState("puter");const [model,setModel]=useState("openai/gpt-oss-20b");const [copied,setCopied]=useState(false);async function go(){if(!answer.trim())return;setBusy(true);try{const r=await api<any>("/api/v1/reasoning/analyze",{method:"POST",body:JSON.stringify({problem,answer,provider,model,language:"English"})});setAnalysis(r.mode==="puter-client"?await runPuter(r.prompt,r.model||model):(r.analysis||r.notice||""))}catch(e:any){setAnalysis(e.message||"Reasoning analysis could not be completed.")}finally{setBusy(false)}}async function copy(){await navigator.clipboard?.writeText(analysis);setCopied(true);setTimeout(()=>setCopied(false),1200)}return <AppLayout><div className="page"><div className="page-head"><div><div className="eyebrow">Reasoning Lab</div><h1>Make the thinking inspectable.</h1><p>Practice assumptions, causality, alternative explanations, trade-offs and verification — not just final answers.</p></div><button className="button" onClick={()=>{setAnswer("");setAnalysis("")}}><RotateCcw size={14}/> Reset</button></div><div className="grid grid-2"><section className="panel"><div className="panel-head"><div><div className="eyebrow">Case</div><h2>Reasoning challenge</h2></div><Brain/></div><div className="question">{problem}</div><div className="field" style={{marginTop:14}}><label>Your reasoning</label><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="State assumptions → causal chain → evidence → alternatives → verification…"/></div><AIControls provider={provider} model={model} onProvider={setProvider} onModel={setModel}/><button className="button primary" onClick={go} disabled={busy||!answer.trim()}>{busy?"Analyzing…":<>Analyze reasoning <ArrowRight size={14}/></>}</button></section><section className="panel"><div className="panel-head"><div><div className="eyebrow">Interpretation</div><h2>Evidence map</h2></div><Brain/></div>{analysis?<><div className="answer-toolbar"><button className="button" onClick={copy}>{copied?<Check size={13}/>:<Copy size={13}/>} {copied?"Copied":"Copy answer"}</button></div><div className="structured-answer">{blocks(analysis).map((b:any,i:number)=><article className={`structured-block ${i===0?"highlight":""}`} key={i}><h3>{b.label}</h3><p>{b.text||"No detail returned."}</p></article>)}</div></>:<div className="empty">Your AI result will be organized into assumptions, causal chain, evidence, alternatives, trade-offs, risks, missing evidence and verification steps.</div>}</section></div></div></AppLayout>}
