import PublicPage from "../../components/PublicPage";

const sections=[
 ["01","Scope","This Privacy Policy describes the data practices of the SKILLsetra application used in the current demo and its configured deployments. The exact storage provider, retention period and operational controls depend on the deployment configuration."],
 ["02","Information you provide","This can include your name, email address, target role, assessment responses, challenge answers, project descriptions, evidence records, self-declared claims, learning progress, interview practice and settings."],
 ["03","Connected services","If you connect GitHub or another supported service, SKILLsetra processes the information required for the feature you explicitly use. Do not submit passwords, API keys, private tokens or other secrets as evidence."],
 ["04","How information is used","Workspace information is used to organize evidence, evaluate submitted work, identify competency gaps, generate practice and learning actions, maintain progress, support project analysis and provide the features you request."],
 ["05","AI-assisted processing","SKILLsetra uses Puter AI as the primary browser-side provider and Ollama as an optional secondary/local provider. AI output is an interpretation or recommendation, not independent proof of competency. Provider availability and model behavior can change."],
 ["06","Evidence and claims","A self-declared claim is stored separately from observed evidence. Connecting a claim to an artifact does not change the underlying artifact into a guaranteed verification. The product is designed to preserve this distinction."],
 ["07","Local demo and production deployments","A local/demo build may store workspace state in browser storage and use seeded data. A production deployment may use Supabase/PostgreSQL or another configured service and should publish its own retention, deletion, backup and access-control commitments."],
 ["08","Your controls","Where enabled, you can review or change profile, evidence, connected-service and application settings. For a production deployment, requests for access, correction or deletion should be sent to the operator responsible for that deployment."],
 ["09","Security limitations","No software system can guarantee absolute security. Use least-privilege credentials, keep tokens out of evidence fields, disconnect integrations you no longer need and do not upload confidential material unless the deployment is approved for it."],
 ["10","Children and sensitive information","SKILLsetra is not designed as a service for collecting unnecessary sensitive personal information. Do not submit highly sensitive information unless a specific deployment has documented a lawful and secure reason to process it."],
 ["11","External provider policies","GitHub, Puter and other external services may process information under their own terms and privacy policies. Their rules are separate from this application policy."],
 ["12","Policy changes and contact","This page may be updated when the application, providers or deployment model changes. Use the Contact page for product or policy questions. This document is an application notice, not jurisdiction-specific legal advice."]
];
export default function Privacy(){return <PublicPage eyebrow="Privacy policy" title="Understand what SKILLsetra uses, why it uses it, and where AI fits."><div className="legal-intro"><p>SKILLsetra is designed around evidence, not silent profiling. The application should make a clear distinction between information you provide, evidence it observes, and interpretation produced by an AI model.</p><div className="legal-meta"><span>Last reviewed: 1 October 2026</span><span>Applies to the current SKILLsetra demo/application build</span></div></div><div className="legal-list">{sections.map(([n,h,p])=><section className="legal-section" key={n}><div className="legal-number">{n}</div><div><h2>{h}</h2><p>{p}</p></div></section>)}</div><aside className="legal-callout"><b>Deployment note</b><span>Before public/commercial deployment, replace demo wording with the operator's actual legal entity, contact channel, retention details and jurisdiction-specific terms.</span></aside><aside className="legal-callout"><b>Need an account or data request?</b><span>Use the Contact page and describe the deployment and request without including passwords, tokens or other credentials.</span></aside></PublicPage>}
