"use client";
import {useEffect,useState} from "react";
import AppLayout from "../../components/AppLayout";
import {api} from "../../lib/api";import {runPuter} from "../../lib/ai";
import {GitBranch,ShieldCheck,Sparkles,LockKeyhole,FileCheck2} from "lucide-react";
export default function GitHub(){
 const [token,setToken]=useState(""); const [savedClaim,setSavedClaim]=useState<number|null>(null); const [account,setAccount]=useState<any>(null); const [url,setUrl]=useState(""); const [analysis,setAnalysis]=useState<any>(null); const [provider,setProvider]=useState("puter"); const [model,setModel]=useState("openai/gpt-oss-20b"); const [models,setModels]=useState<any[]>([]); const [loading,setLoading]=useState(false);
 useEffect(()=>{api<any>("/api/github").then((r:any)=>{if(r.connection?.connected)setAccount(r)}).catch(()=>{});api("/api/github/analysis").then(setAnalysis).catch(()=>{});api("/api/v1/ai/models?provider=puter").then((x:any)=>setModels(x.models||[])).catch(()=>{})},[]);
 async function connect(){setLoading(true);try{const r=await api("/api/github/connect",{method:"POST",body:JSON.stringify({token})});setAccount(r);setToken("")}catch(e:any){alert(e.message||"GitHub connection failed")}finally{setLoading(false)}}
 async function disconnect(){await api("/api/github/disconnect",{method:"POST"}).catch(()=>{});setAccount(null);setToken("")}
 async function analyze(target:string){setLoading(true);try{const r=await api<any>("/api/github/analyze",{method:"POST",body:JSON.stringify({url:target,provider,model,language:"English"})});if(r.ai?.mode==="puter-client"&&r.ai.prompt){r.ai.text=await runPuter(r.ai.prompt,r.ai.model||model);r.ai.provider="puter"}setAnalysis(r)}catch(e:any){alert(e.message||"GitHub analysis failed")}finally{setLoading(false)}}
 return <AppLayout><div className="page"><div className="page-head"><div><div className="eyebrow">Repository intelligence</div><h1>GitHub, with evidence.</h1><p>Connect a GitHub account or analyze a public repository. SKILLSETRA separates observed facts, interpretation and uncertainty.</p></div></div><section className="github-layout">
 <div className="panel"><div className="panel-head"><div><GitBranch/><h2>Connect GitHub</h2></div><LockKeyhole size={15}/></div><p className="muted" style={{fontSize:10}}>Use a GitHub token with read-only repository metadata access. SKILLSETRA does not display the token after connection.</p><div className="field"><label>GitHub token</label><input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="github_pat_…"/></div><button className="button primary" onClick={connect} disabled={!token||loading}>Connect account</button>{account&&<><div className="action-row" style={{marginTop:10}}><button className="button" onClick={disconnect}>Disconnect GitHub</button></div><div className="signal good" style={{marginTop:14}}><span>Connected as</span><b>{account.username}</b></div><div className="repo-list" style={{marginTop:12}}>{(account.repositories||[]).map((r:any)=><div className="repo" key={r.id} onClick={()=>analyze(r.html_url)}><b>{r.name}</b><p>{r.description}</p><span className="tag">{r.language}</span></div>)}</div></>}</div>
 <div className="panel"><div className="panel-head"><div><div className="eyebrow">Public repository analysis</div><h2>Analyze a repo</h2></div><Sparkles/></div><div className="field"><label>Repository URL</label><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://github.com/owner/repository"/></div><div className="form-grid" style={{marginTop:10}}><div className="field"><label>AI provider</label><select value={provider} onChange={e=>setProvider(e.target.value)}><option value="puter">Puter AI · Primary</option><option value="ollama">Ollama · Secondary</option></select></div><div className="field"><label>AI model</label><select value={model} onChange={e=>setModel(e.target.value)}>{(models.length?models:[{id:model,label:model}]).map((m:any)=><option key={m.id} value={m.id}>{m.label||m.id}</option>)}</select></div></div><button className="button primary" style={{marginTop:12}} onClick={()=>analyze(url)} disabled={!url||loading}>Analyze repository</button>
 {analysis?.facts&&<div style={{marginTop:18}}><div className="panel" style={{padding:15}}><div className="eyebrow">Observed repository</div><h2>{analysis.facts.repository}</h2><div className="signal-grid"><div className="signal"><span>Languages</span><b>{analysis.facts.languages?.join(", ")||"None"}</b></div><div className="signal"><span>Signals</span><b>{analysis.facts.signals?.join(", ")||"None"}</b></div><div className="signal"><span>Tests</span><b>{analysis.facts.has_tests?"Detected":"Not detected"}</b></div><div className="signal"><span>CI/CD</span><b>{analysis.facts.has_ci?"Detected":"Not detected"}</b></div></div></div><div style={{marginTop:12}}>{(analysis.claims||[]).map((c:any,i:number)=><div className="claim" key={i}><b>{c.claim}</b><p>Evidence: {c.evidence?.join(" · ")}</p><span className="tag">{c.confidence} confidence</span><p>Limitation: {c.limitation}</p><button className="button" style={{marginTop:8}} disabled={savedClaim===i} onClick={async()=>{try{await api("/api/evidence/claims",{method:"POST",body:JSON.stringify({claim:c.claim,competency:c.competency||"Engineering",target_role:"",evidence_title:analysis.facts.repository,evidence_description:(c.evidence||[]).join("; "),evidence_type:"GitHub repository",evidence_url:url,existing_evidence_id:analysis.evidence_id||""})});setSavedClaim(i)}catch(e:any){alert(e.message||"Could not add this claim to Evidence.")}}}><FileCheck2 size={13}/>{savedClaim===i?"Added to Evidence":"Add claim to Evidence"}</button></div>)}</div>{analysis.ai?.text&&<div className="panel" style={{marginTop:12}}><div className="eyebrow">AI interpretation · {analysis.ai.provider}</div><p className="evaluation">{analysis.ai.text}</p></div>}<div className="panel" style={{marginTop:12}}><div className="eyebrow">Improvement suggestions</div>{(analysis.suggestions||[]).map((s:any,i:number)=><div className="timeline-item" style={{marginTop:12}} key={i}><div className="timeline-dot"><ShieldCheck size={13}/></div><div><b>{s.title}</b><p>{s.why}</p><small>Proof artifact: {s.proof}</small></div></div>)}</div></div>}
 </div></section></div></AppLayout>
}
