"use client";
import {useEffect,useMemo,useState} from "react";
import AppLayout from "../../components/AppLayout";
import {api} from "../../lib/api";
import {runPuter} from "../../lib/ai";
import {Mic2,Play,Send,Sparkles,Timer,RotateCcw,ChevronRight,Volume2,ShieldCheck,Brain,BarChart3} from "lucide-react";

const types=["Technical","Coding","System Design","Behavioral / HR","Managerial","Case Study","AI / ML","Mixed"];
const focusAreas=["Role fundamentals","Problem solving","Debugging","System design","Communication","AI / ML","Projects / resume","Security","Performance","Mixed"];
const modes=["Mock interview","Pressure round","Rapid fire","Panel simulation","Socratic deep dive","Hiring-manager round"];
const difficulties=["Adaptive","Beginner","Intermediate","Advanced","Expert"];

type Provider={id:string;name:string;tier:string;model:string;status:string;connected:boolean;server_side:boolean;models:any[]};
export default function Interview(){
 const [type,setType]=useState("Technical"),[role,setRole]=useState("Software Developer"),[level,setLevel]=useState("Intermediate"),[company,setCompany]=useState(""),[focus,setFocus]=useState("Role fundamentals"),[mode,setMode]=useState("Mock interview"),[difficulty,setDifficulty]=useState("Adaptive");
 const [provider,setProvider]=useState("puter"),[model,setModel]=useState("openai/gpt-oss-20b"),[providers,setProviders]=useState<Provider[]>([]),[models,setModels]=useState<any[]>([]);
 const [q,setQ]=useState(""),[answer,setAnswer]=useState(""),[evaluation,setEvaluation]=useState<any>(),[session,setSession]=useState(""),[round,setRound]=useState(0),[total,setTotal]=useState(5),[history,setHistory]=useState<any[]>([]),[busy,setBusy]=useState(false),[seconds,setSeconds]=useState(0),[started,setStarted]=useState(false),[listening,setListening]=useState(false);
 useEffect(()=>{api<any>("/api/v1/ai/providers").then(x=>{setProviders(x.providers||[]);const d=x.providers?.find((p:any)=>p.id===(x.default||"puter"))||x.providers?.[0];if(d){setProvider(d.id);setModel(d.model||"")}}).catch(()=>{})},[]);
 useEffect(()=>{api<any>(`/api/v1/ai/models?provider=${encodeURIComponent(provider)}`).then(x=>{setModels(x.models||[]);if(x.models?.length&&!x.models.some((m:any)=>m.id===model))setModel(x.models[0].id)}).catch(()=>setModels([]))},[provider]);
 useEffect(()=>{if(!started||!q)return;const id=window.setInterval(()=>setSeconds(x=>x+1),1000);return()=>window.clearInterval(id)},[started,q]);
 const providerInfo=useMemo(()=>providers.find(p=>p.id===provider),[providers,provider]);
 const mm=Math.floor(seconds/60).toString().padStart(2,"0"),ss=(seconds%60).toString().padStart(2,"0");
 const scrollTop=()=>window.requestAnimationFrame(()=>window.scrollTo({top:0,behavior:"auto"}));
 async function start(nextRound=1){setBusy(true);try{const r=await api<any>("/api/v1/interview/start",{method:"POST",body:JSON.stringify({role,interview_type:type,level,language:"English",provider,model,company,focus,mode,difficulty,question_number:nextRound,total_questions:total})});let question=r.question||"";if(r.mode==="puter-client"&&r.prompt)question=await runPuter(r.prompt,r.model||model);setQ(question);setSession(r.session_id||"");setEvaluation(null);setAnswer("");setRound(nextRound);setStarted(true);setSeconds(0);scrollTop()}catch(e:any){setQ("Unable to start this round. Check the selected AI provider.")}finally{setBusy(false)}}
 async function evaluate(){if(!session||!q.trim()){setEvaluation({evaluation:"No active interview question is available. Start a new interview round first."});return}if(!answer.trim())return;setBusy(true);try{const r=await api<any>("/api/v1/interview/evaluate",{method:"POST",body:JSON.stringify({session_id:session,question:q,answer,language:"English",provider,model})});let data=r;if(r.mode==="puter-client"&&r.prompt){const raw=await runPuter(r.prompt,r.model||model);data={mode:"live",evaluation:raw,provider:"puter"}}setEvaluation(data);scrollTop();setHistory(h=>[...h,{round,question:q,answer,evaluation:data.structured||data.evaluation||data.notice||"No evaluation returned."}])}catch(e){setEvaluation({evaluation:"Evaluation could not be completed. Try another enabled provider."})}finally{setBusy(false)}}
 function voice(){const Speech=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!Speech){setAnswer(a=>a+"\n[Voice input is not supported by this browser]");return}const rec=new Speech();rec.lang="en-IN";rec.interimResults=false;rec.continuous=false;setListening(true);rec.onresult=(e:any)=>setAnswer(a=>(a?a+" ":"")+e.results[0][0].transcript);rec.onerror=()=>setListening(false);rec.onend=()=>setListening(false);rec.start()}
 function reset(){setQ("");setAnswer("");setEvaluation(null);setHistory([]);setRound(0);setStarted(false);setSeconds(0)}
 const structured=evaluation?.structured;
 return <AppLayout><div className="page"><div className="page-head"><div><div className="eyebrow">AI Interviewer · Interview OS</div><h1>Practice the room before the room.</h1><p>Run realistic multi-round interviews with adaptive difficulty, reasoning-first questions, voice input, structured evaluation and follow-up pressure.</p></div><button className="button" onClick={reset}><RotateCcw size={14}/> Reset</button></div>
 <div className="interview-layout"><div className="panel"><div className="panel-head"><div><Mic2/><h2>Interview setup</h2></div><Sparkles/></div>
 <div className="field"><label>Role</label><input value={role} onChange={e=>setRole(e.target.value)} placeholder="e.g. AI Engineer"/></div>
 <div className="field" style={{marginTop:10}}><label>Company / context</label><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Optional context"/></div>
 <div className="grid grid-2" style={{marginTop:10}}><div className="field"><label>Level</label><select value={level} onChange={e=>setLevel(e.target.value)}><option>Entry</option><option>Intermediate</option><option>Senior</option><option>Lead</option></select></div><div className="field"><label>Difficulty</label><select value={difficulty} onChange={e=>setDifficulty(e.target.value)}>{difficulties.map(x=><option key={x}>{x}</option>)}</select></div></div>
 <div className="field" style={{marginTop:10}}><label>Interview mode</label><select value={mode} onChange={e=>setMode(e.target.value)}>{modes.map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="field" style={{marginTop:10}}><label>AI provider</label><select value={provider} onChange={e=>setProvider(e.target.value)}>{providers.map(p=><option key={p.id} value={p.id}>{p.name} · {p.tier}{p.connected?" · ready":""}</option>)}</select><small>{providerInfo?.status}</small></div>
 <div className="field" style={{marginTop:10}}><label>Model</label><select value={model} onChange={e=>setModel(e.target.value)}>{(models.length?models:[{id:model,label:model}]).map((m:any)=><option key={m.id} value={m.id}>{m.label||m.id}{m.recommended?" · recommended":""}</option>)}</select></div>
 <div className="field" style={{marginTop:10}}><label>Rounds</label><select value={total} onChange={e=>setTotal(Number(e.target.value))}><option value={1}>1 · Quick practice</option><option value={3}>3 · Short mock</option><option value={5}>5 · Full mock</option><option value={10}>10 · Deep mock</option><option value={15}>15 · Interview loop</option></select></div>
 <div className="field" style={{marginTop:10}}><label>Focus</label><select value={focus} onChange={e=>setFocus(e.target.value)}>{focusAreas.map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="eyebrow" style={{marginTop:18}}>Question family</div><div className="interview-types" style={{marginTop:8}}>{types.map(x=><button className={type===x?"active":""} key={x} onClick={()=>setType(x)}>{x}</button>)}</div>
 <button className="button primary" style={{width:"100%",marginTop:14}} onClick={()=>start(1)} disabled={busy}><Play/> {busy?"Starting…":"Start interview"}</button>
 </div>
 <div className="panel"><div className="panel-head"><div><div className="eyebrow">Live session {round?`· Question ${round}/${total}`:""}</div><h2>{type} · {role}</h2></div>{q&&<span className="tag good"><Timer size={12}/> {mm}:{ss}</span>}</div>
 {q?<><div className="question"><div className="eyebrow">Question {round} · {mode} · {difficulty}</div>{q}</div><div className="field" style={{marginTop:15}}><label>Your answer</label><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Structure: answer → reasoning → evidence → trade-off → verification…"/><div className="action-row" style={{marginTop:8}}><button className="button" onClick={voice}><Volume2 size={13}/> {listening?"Listening…":"Voice answer"}</button><span className="tag">{answer.trim().split(/\s+/).filter(Boolean).length} words</span></div></div><div className="action-row"><button className="button primary" onClick={evaluate} disabled={!answer.trim()||busy}><Send/> {busy?"Evaluating…":"Evaluate answer"}</button>{evaluation&&round<total&&<button className="button" onClick={()=>start(round+1)} disabled={busy}>Next question <ChevronRight size={14}/></button>}</div>
 {evaluation&&<div className="panel" style={{marginTop:15}}><div className="panel-head"><div><div className="eyebrow">Evaluation · evidence-first rubric</div><h2><BarChart3 size={16}/> Feedback</h2></div><ShieldCheck/></div>{structured?<><div className="grid grid-3">{[["Overall",structured.overall_score_10],["Correctness",structured.correctness],["Reasoning",structured.reasoning],["Structure",structured.structure],["Communication",structured.communication],["Evidence",structured.evidence],["Trade-offs",structured.tradeoffs]].map(([k,v]:any)=><div className="signal" key={k}><b>{k}</b><span>{v??"—"}/10</span></div>)}</div><div className="grid grid-2" style={{marginTop:12}}><div className="signal"><b>Strengths</b><span>{(structured.strengths||[]).join(" · ")||"—"}</span></div><div className="signal"><b>Gaps</b><span>{(structured.gaps||[]).join(" · ")||"—"}</span></div><div className="signal"><b>Assumptions</b><span>{(structured.assumptions||[]).join(" · ")||"—"}</span></div><div className="signal"><b>Improved outline</b><span>{(structured.improved_outline||[]).join(" → ")||"—"}</span></div></div><div className="question" style={{marginTop:12}}><b>Follow-up:</b> {structured.follow_up_question||"Use the next round to probe the weakest dimension."}</div></>:<div className="evaluation">{evaluation.evaluation||evaluation.notice||"Evaluation unavailable."}</div>}</div>}
 {history.length>0&&<div style={{marginTop:18}}><div className="eyebrow">Session history</div><div className="grid grid-2" style={{marginTop:8}}>{history.map((h:any,i:number)=><article className="signal" key={i}><b>Round {h.round}</b><span>{typeof h.evaluation==="string"?h.evaluation.slice(0,260):JSON.stringify(h.evaluation).slice(0,260)}</span></article>)}</div></div>}
 </>:<div className="empty"><Mic2 size={30}/><h3>Ready when you are.</h3><p>Pick a question family, difficulty and interview mode. SKILLSETRA will alternate fundamentals, applied cases, debugging, trade-offs and follow-ups across a multi-round session.</p></div>}
 </div></div></div></AppLayout>
}
