"use client";
import {useEffect,useState,type FormEvent} from "react";
import AppLayout from "../../components/AppLayout";
import {api} from "../../lib/api";
import {runPuter} from "../../lib/ai";
import {CheckCircle2,ClipboardCheck,FileCheck2,Plus,ShieldCheck,Target,Download,RefreshCw} from "lucide-react";
type TargetEvidence={competency:string;status:string;evidence_count:number;claim_count:number;recommended_proof:string};
export default function Evidence(){
 const [data,setData]=useState<any>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[aiReview,setAiReview]=useState<any>(null);
 const [claim,setClaim]=useState({claim:"",competency:"",target_role:"",evidence_title:"",evidence_description:"",evidence_type:"Project artifact",evidence_url:"",existing_evidence_id:""}); const [reviewing,setReviewing]=useState("");
 async function load(){setLoading(true);try{setData(await api<any>("/api/v1/evidence"))}catch(e:any){setMessage(e.message||"Evidence workspace could not be loaded.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(data&&!claim.target_role)setClaim(x=>({...x,target_role:data.target_role||""}))},[data,claim.target_role]);
 async function submit(e:FormEvent){e.preventDefault();if(!claim.claim.trim()||!claim.competency.trim())return;if(claim.existing_evidence_id&&claim.evidence_description.trim().length<10){setMessage("Describe the linked artifact and how it was verified.");return;}setSaving(true);setMessage("AI is automatically reviewing your evidence…");setAiReview(null);try{const r=await api<any>("/api/v1/evidence/claims",{method:"POST",body:JSON.stringify(claim)});let final=r;if(r.ai?.mode==="puter-client"&&r.ai.prompt){try{const raw=await runPuter(r.ai.prompt,r.ai.model||"openai/gpt-oss-20b");final=await api<any>(`/api/v1/evidence/claims/${r.claim.id}/ai-review`,{method:"POST",body:JSON.stringify({result:raw,provider:"puter"})});}catch{final=await api<any>(`/api/v1/evidence/claims/${r.claim.id}/ai-review`,{method:"POST",body:JSON.stringify({result:"{\"supported\":false,\"confidence\":\"none\",\"message\":\"No detected evidence. AI providers were unavailable for this review.\",\"detected\":[]}",provider:"none"})});}}const review=final.ai?.review||final.ai||r.ai?.review||r.ai||null;setAiReview(review);const supported=Boolean(final.claim?.ai_review?.supported);setMessage(supported?`AI detected supporting evidence. Your ${claim.competency} evidence progression changed by ${final.claim?.progress_delta>0?"+":""}${final.claim?.progress_delta||0} points.`:`No detected evidence for this claim. Your progression was adjusted based on the AI review.`);setClaim(x=>({...x,claim:"",evidence_title:"",evidence_description:"",evidence_url:"",existing_evidence_id:""}));await load()}catch(e:any){setMessage(e.message||"AI evidence review could not be completed. No evidence was automatically verified.")}finally{setSaving(false)}}
 function exportEvidence(){if(!data)return;const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="skillsetra-evidence.json";a.click();URL.revokeObjectURL(url)}
 if(loading)return <AppLayout><div className="page"><div className="empty">Loading your evidence workspace…</div></div></AppLayout>;
 return <AppLayout><div className="page">
  <div className="page-head"><div><div className="eyebrow">Evidence Intelligence</div><h1>Claim it. Target it. Prove it.</h1><p>SKILLSETRA compares the claim with the supplied answer/evidence, scores the evidence, records detected signals, and updates competency progression from the review.</p></div><div className="action-row"><button className="button" onClick={load}><RefreshCw size={13}/> Refresh</button><button className="button" onClick={exportEvidence}><Download size={13}/> Export evidence</button></div></div>
  {message&&<div className="notice" role="status">{message}</div>}
  {aiReview&&<section className="panel" style={{marginBottom:16}}><div className="panel-head"><div><div className="eyebrow">Automatic AI evidence review · {aiReview.provider||"AI"}</div><h2>{aiReview.supported?"Evidence detected":"No detected evidence"}</h2></div><ShieldCheck/></div><p className="muted">{aiReview.message||"The AI review completed."}</p><div className="action-row"><span className="tag blue">Evidence score {aiReview.evidence_score??0}/100</span><span className="tag">Claim match: {aiReview.claim_match||"unknown"}</span><span className="tag">Ownership {aiReview.ownership_score??0}%</span><span className="tag">Verification {aiReview.verification_score??0}%</span></div>{Array.isArray(aiReview.detected)&&aiReview.detected.length>0&&<div className="grid grid-2">{aiReview.detected.map((x:any,i:number)=><div className="signal good" key={i}><b>Detected signal</b><span>{typeof x==='string'?x:JSON.stringify(x)}</span></div>)}</div>}<div className="action-row"><span className={`tag ${aiReview.supported?'good':'warn'}`}>{aiReview.supported?'AI-SUPPORTED':'NO DETECTION'}</span><span className="tag">{aiReview.confidence||'none'} confidence</span>{data?.summary?.goal_progress!==undefined&&<span className="tag blue">Goal progression {data.summary.goal_progress}%</span>}</div></section>}
  <div className="grid grid-4 evidence-summary"><article className="metric-card"><span className="eyebrow">Evidence events</span><strong>{data?.summary?.total_evidence||0}</strong><small>Recorded artifacts and activities</small></article><article className="metric-card"><span className="eyebrow">Claims</span><strong>{data?.summary?.claims||0}</strong><small>Self-declared claims in this workspace</small></article><article className="metric-card"><span className="eyebrow">Target covered</span><strong>{data?.summary?.covered||0}</strong><small>Role competencies with evidence</small></article><article className="metric-card"><span className="eyebrow">Target gaps</span><strong>{(data?.summary?.missing||0)+(data?.summary?.claimed||0)}</strong><small>Missing or claim-only requirements</small></article></div>
  <div className="grid grid-2 evidence-layout">
   <section className="panel"><div className="panel-head"><div><div className="eyebrow">Claim evidence</div><h2>Make a competency claim</h2></div><FileCheck2/></div><p className="muted">State what you believe you can do. You can link an already-observed artifact; otherwise the claim stays separate from verified evidence.</p>
    <form onSubmit={submit} className="form-grid">
      <div className="field full"><label>YOUR CLAIM</label><input value={claim.claim} onChange={e=>setClaim(x=>({...x,claim:e.target.value}))} placeholder="I can design and test reliable REST APIs." /></div>
      <div className="field"><label>COMPETENCY</label><input value={claim.competency} onChange={e=>setClaim(x=>({...x,competency:e.target.value}))} placeholder="APIs" /></div>
      <div className="field"><label>TARGET ROLE</label><input value={claim.target_role} onChange={e=>setClaim(x=>({...x,target_role:e.target.value}))} /></div>
      <div className="field"><label>EVIDENCE TYPE</label><select value={claim.evidence_type} onChange={e=>setClaim(x=>({...x,evidence_type:e.target.value}))}>{["Project artifact","GitHub repository","Assessment","Challenge","Interview","Project defense","Learning completion","Other"].map(x=><option key={x}>{x}</option>)}</select></div>
      <div className="field"><label>EVIDENCE TITLE</label><input value={claim.evidence_title} onChange={e=>setClaim(x=>({...x,evidence_title:e.target.value}))} placeholder="API test suite and project" /></div>
      <div className="field"><label>LINK EXISTING OBSERVED EVIDENCE</label><select value={claim.existing_evidence_id} onChange={e=>setClaim(x=>({...x,existing_evidence_id:e.target.value}))}><option value="">No existing artifact — claim only</option>{(data?.ledger||[]).filter((e:any)=>!e.claim_id).map((e:any)=><option key={e.id} value={e.id}>{e.activity} · {e.competency} · {e.date}</option>)}</select></div>
      <div className="field full"><label>WHAT THE EVIDENCE SHOWS</label><textarea className="big-textarea" value={claim.evidence_description} onChange={e=>setClaim(x=>({...x,evidence_description:e.target.value}))} placeholder="Describe the observable artifact, what you personally did, and how the result was verified…" /></div>
      <div className="field full"><label>OPTIONAL EVIDENCE URL</label><input type="url" value={claim.evidence_url} onChange={e=>setClaim(x=>({...x,evidence_url:e.target.value}))} placeholder="https://github.com/..." /></div>
      <div className="action-row"><button className="button primary" disabled={saving}><Plus size={14}/>{saving?"Recording…":claim.existing_evidence_id?"Link claim to evidence":"Record claim"}</button></div>
    </form>
   </section>
   <section className="panel"><div className="panel-head"><div><div className="eyebrow">Target evidence</div><h2>{data?.target_role||"Target role"}</h2></div><Target/></div><p className="muted">These are the evidence areas SKILLSETRA expects for your current target role. A claim is not the same as coverage.</p><div className="target-list">{(data?.target_evidence||[]).map((x:TargetEvidence)=><article className="target-evidence" key={x.competency}><div className="target-evidence-head"><div><b>{x.competency}</b><small>{x.evidence_count} evidence · {x.claim_count} claim</small></div><span className={`tag ${x.status==='covered'?'good':x.status==='claimed'?'warn':''}`}>{x.status.toUpperCase()}</span></div><p>{x.recommended_proof}</p></article>)}</div></section>
  </div>
  <section className="panel"><div className="panel-head"><div><div className="eyebrow">Evidence ledger</div><h2>What has actually been recorded</h2><p className="muted" style={{fontSize:10,margin:0}}>Each item keeps its source, date, confidence and status visible. Review is a human review state, not automatic verification.</p></div><ShieldCheck/></div>{(data?.ledger||[]).length?<div className="evidence-table">{data.ledger.map((e:any)=><article className="evidence-row" key={e.id}><div className="evidence-icon"><CheckCircle2 size={15}/></div><div><b>{e.activity}</b><span>{e.competency} · {e.date} · {e.evidence_type||"Workspace event"}</span><p>{e.evidence}</p>{e.source_url&&<a href={e.source_url} target="_blank" rel="noreferrer" className="evidence-source">Open source evidence ↗</a>}</div><div className="evidence-meta"><span className={`tag ${String(e.result||"").toLowerCase().includes("strong")?"good":String(e.result||"").toLowerCase().includes("claim")?"warn":""}`}>{e.result||"Observed"}</span><small>{e.confidence||"Unknown"} confidence</small></div></article>)}</div>:<div className="empty">No evidence has been recorded yet.</div>}</section>
  <section className="panel"><div className="panel-head"><div><div className="eyebrow">Claim register</div><h2>Claims waiting for stronger proof</h2></div><FileCheck2/></div>{(data?.claims||[]).length?<div className="claims-register">{data.claims.map((c:any)=><article className="claim-register" key={c.id}><div><b>{c.claim}</b><span>{c.competency} · {c.target_role||data.target_role} · {c.created_at}{c.evidence_id?` · linked to ${c.evidence_id}`:" · no observed artifact linked"}</span></div><div className="evidence-meta"><span className={`tag ${c.status==='reviewed'?'blue':'warn'}`}>{c.status==='reviewed'?'REVIEWED':c.status==='ai-supported'?'AI-SUPPORTED':c.status==='no-detection'?'NO DETECTION':'REVIEWING'}</span>{c.status!=='reviewed'&&<button className="button" disabled={reviewing===c.id} onClick={async()=>{setReviewing(c.id);try{await api(`/api/v1/evidence/claims/${c.id}/review`,{method:'POST'});await load()}catch(e:any){setMessage(e.message||'Could not review the claim.')}finally{setReviewing('')}}}>{reviewing===c.id?'Saving…':'Mark reviewed'}</button>}</div></article>)}</div>:<div className="empty">No claims yet. Add a claim only when you can point to a concrete artifact.</div>}</section>
  <section className="panel evidence-principles"><div className="panel-head"><div><div className="eyebrow">Evidence rules</div><h2>How SKILLSETRA keeps claims credible</h2></div><ClipboardCheck/></div><div className="grid grid-3"><div className="signal"><b>Observed ≠ inferred</b><span>Recorded artifacts and events are separated from AI interpretation.</span></div><div className="signal"><b>Claimed ≠ verified</b><span>A self-declared capability stays low-confidence until stronger evidence is connected.</span></div><div className="signal"><b>Target ≠ prediction</b><span>Target evidence describes what to prove for a role; it does not predict hiring outcomes.</span></div></div></section>
 </div></AppLayout>
}
