"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {usePathname,useRouter,useSearchParams} from 'next/navigation';
import {Menu,PanelLeftClose,PanelLeftOpen,Search,X,Sun,Moon,MoreHorizontal,Bell,Home,LayoutDashboard,BrainCircuit,FolderKanban,Github,Mic2,BookOpen,BriefcaseBusiness,Settings2,FileCheck2,BarChart3} from 'lucide-react';
import {RequireAuth,useApp} from './AppProvider';
import Logo from './Logo';
import PersistentAIWidget from './PersistentAIWidget';
import {NAVIGATION,GROUPS,searchNavigation} from './navigation';
import {api} from '../lib/api';

function ShellInner({children}:{children:React.ReactNode}){
 const pathname=usePathname(); const searchParams=useSearchParams(); const router=useRouter(); const {user,demo,theme,setTheme}=useApp();
 const [collapsed,setCollapsed]=useState(false),[mobile,setMobile]=useState(false),[query,setQuery]=useState(''),[searchOpen,setSearchOpen]=useState(false),[more,setMore]=useState(false),[quickOpen,setQuickOpen]=useState(false),[notifications,setNotifications]=useState<any[]>([]),[notifOpen,setNotifOpen]=useState(false),[dataResults,setDataResults]=useState<any[]>([]);
 const searchRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{setCollapsed(localStorage.getItem('skillsetra:sidebar')==='1');},[]);
 useEffect(()=>{localStorage.setItem('skillsetra:sidebar',collapsed?'1':'0');},[collapsed]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(true);searchRef.current?.focus()} if(e.key==='Escape'){setSearchOpen(false);setNotifOpen(false);setMore(false);setQuickOpen(false);setMobile(false)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[]);
 useEffect(()=>{api<any>('/api/v1/notifications').then(r=>setNotifications(r.items||[])).catch(()=>setNotifications([]));},[pathname]);
 const navResults=useMemo(()=>searchNavigation(query),[query]);
 useEffect(()=>{if(!query.trim()){setDataResults([]);return}const t=window.setTimeout(()=>api<any>(`/api/v1/search?q=${encodeURIComponent(query)}`).then(r=>setDataResults(r.items||[])).catch(()=>setDataResults([])),180);return()=>window.clearTimeout(t)},[query]);
 const results=[...navResults.map(n=>({id:`nav-${n.id}`,label:n.label,group:n.group,href:n.href,icon:n.icon,description:'Product destination'})),...dataResults.map(x=>({id:`data-${x.type}-${x.id}`,label:x.title,group:x.type.toUpperCase(),href:x.href,icon:Search,description:x.description}))].slice(0,12);
 const activeNavId=useMemo(()=>{const view=searchParams.get('view')||'';const exactQuery=NAVIGATION.filter(n=>{const [path,q]=n.href.split('?');if(path!==pathname||!q)return false;const expected=new URLSearchParams(q);return Array.from(expected.entries()).every(([k,v])=>searchParams.get(k)===v)});if(exactQuery.length)return exactQuery[0].id;const exactPath=NAVIGATION.find(n=>{const [path,q]=n.href.split('?');return path===pathname&&!q});if(exactPath&&!['evidence','resources','practice','roles','jobs','analytics'].includes(view))return exactPath.id;const parents=NAVIGATION.filter(n=>!n.href.includes('?')).filter(n=>{const path=n.href;return path!=='/'&&pathname.startsWith(path+'/')}).sort((a,b)=>b.href.length-a.href.length);return parents[0]?.id||'main'},[pathname,searchParams]);
 const isActive=(href:string)=>{const item=NAVIGATION.find(n=>n.href===href);return Boolean(item&&item.id===activeNavId)};
 const go=(href:string)=>{setQuery('');setSearchOpen(false);setQuickOpen(false);setMobile(false);router.push(href)};
 return <div className={`product-shell ${collapsed?'sidebar-collapsed':''} ${demo?'is-demo':''}`}><a className="skip-link" href="#main-content">Skip to content</a>
  <aside className="product-sidebar" aria-label="Primary navigation">
   <div className="sidebar-brand"><Link href="/" className="sidebar-wordmark">SKILLsetra</Link><button onClick={()=>setCollapsed(v=>!v)} aria-label={collapsed?'Open sidebar':'Close sidebar'} title={collapsed?'Open sidebar':'Close sidebar'}>{collapsed?<PanelLeftOpen/>:<PanelLeftClose/>}</button></div>
   <div className="sidebar-scroll">{GROUPS.map(group=><section key={group} className="nav-group"><div className="nav-group-title">{group}</div>{NAVIGATION.filter(n=>n.group===group).map(n=>{const Icon=n.icon;return <Link key={n.id} href={n.href} className={`nav-item ${isActive(n.href)?'active':''}`} title={collapsed?n.label:undefined} onClick={()=>setMobile(false)}><Icon aria-hidden="true"/><span>{n.label}</span></Link>})}</section>)}</div>
   <div className="sidebar-footer">{demo?<div className="demo-badge">DEMO MODE · LOCAL DATA</div>:<div className="demo-badge live">PRODUCTION MODE</div>}</div>
  </aside>
  {mobile&&<div className="mobile-scrim" onClick={()=>setMobile(false)}><aside className="mobile-sidebar" onClick={e=>e.stopPropagation()}><div className="sidebar-brand"><Link href="/" className="sidebar-wordmark">SKILLsetra</Link><button onClick={()=>setMobile(false)} aria-label="Close navigation"><X/></button></div>{GROUPS.map(group=><section key={group} className="nav-group"><div className="nav-group-title">{group}</div>{NAVIGATION.filter(n=>n.group===group).map(n=>{const Icon=n.icon;return <Link key={n.id} href={n.href} className={`nav-item ${isActive(n.href)?'active':''}`} onClick={()=>setMobile(false)}><Icon/><span>{n.label}</span></Link>})}</section>)}</aside></div>}
  <header className="product-topbar"><div className="topbar-main"><Logo compact/><button className="mobile-menu-button" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu/></button><div className="breadcrumb">{NAVIGATION.find(n=>isActive(n.href))?.label||'Main'}</div><nav className="top-feature-links" aria-label="Main features"><Link href="/dashboard">Dashboard</Link><Link href="/evidence">Evidence</Link><Link href="/challenges">Challenges</Link></nav><div className="main-menu-wrap"><button className="main-button" onClick={()=>setQuickOpen(v=>!v)} aria-expanded={quickOpen}><Home size={15}/> Main <span>⌄</span></button>{quickOpen&&<div className="quick-access"><div className="quick-title">MAIN FEATURES</div><button onClick={()=>go("/dashboard")}><LayoutDashboard/>Dashboard</button><button onClick={()=>go("/evidence")}><FileCheck2/>Evidence</button><button onClick={()=>go("/challenges")}><BrainCircuit/>Challenges</button><button onClick={()=>go("/practice")}><FileCheck2/>Practice</button><button onClick={()=>go("/projects")}><FolderKanban/>Projects</button><button onClick={()=>go("/github")}><Github/>GitHub Intelligence</button><button onClick={()=>go("/interview")}><Mic2/>AI Interviewer</button><button onClick={()=>go("/learn")}><BookOpen/>Learning</button><button onClick={()=>go("/career")}><BriefcaseBusiness/>Career</button><button onClick={()=>go("/analytics")}><BarChart3/>Analytics</button><button onClick={()=>go("/settings")}><Settings2/>Settings</button></div>}</div><div className={`global-search ${searchOpen?'open':''}`}><Search/><input ref={searchRef} value={query} onFocus={()=>setSearchOpen(true)} onChange={e=>{setQuery(e.target.value);setSearchOpen(true)}} onKeyDown={e=>{if(e.key==='Enter'&&results[0])go(results[0].href);if(e.key==='Escape'){setQuery('');setSearchOpen(false)}}} placeholder="Search features, evidence, projects…" aria-label="Search SKILLSETRA"/><kbd>Ctrl K</kbd>{searchOpen&&query&&<div className="global-search-results" role="listbox">{results.length?results.map(n=>{const Icon=n.icon;return <button key={n.id} onClick={()=>go(n.href)}><Icon/><span><b>{n.label}</b><small>{n.group} · {n.description}</small></span></button>}):<div className="search-empty">No matching SKILLSETRA destination.</div>}</div>}</div></div>
   <div className="topbar-actions"><button className="icon-button" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label={`Switch to ${theme==='dark'?'light':'dark'} theme`} title={`Switch to ${theme==='dark'?'light':'dark'} theme`}>{theme==='dark'?<Sun/>:<Moon/>}</button><div className="notification-wrap"><button className="icon-button" onClick={()=>setNotifOpen(v=>!v)} aria-label="Notifications"><Bell/>{notifications.some(n=>!n.read)&&<i/>}</button>{notifOpen&&<div className="notification-popover"><div className="popover-title"><span>Notifications</span>{notifications.some(n=>!n.read)&&<button className="popover-action" onClick={async()=>{await Promise.all(notifications.filter(n=>!n.read).map(n=>api(`/api/v1/notifications/${n.id}/read`,{method:"POST"}).catch(()=>null)));setNotifications(x=>x.map(n=>({...n,read:true})))}}>Mark all read</button>}</div>{notifications.length?notifications.slice(0,6).map(n=><button className={`notification-item ${n.read?"read":""}`} key={n.id} onClick={async()=>{if(!n.read){await api(`/api/v1/notifications/${n.id}/read`,{method:"POST"}).catch(()=>{});setNotifications(x=>x.map(v=>v.id===n.id?{...v,read:true}:v))}}}><b>{n.title}</b><span>{n.body}</span></button>):<div className="search-empty">No notifications.</div>}</div>}</div><button className="icon-button mobile-more" onClick={()=>setMore(v=>!v)} aria-label="More controls"><MoreHorizontal/></button><div className="account-menu"><Link href="/profile" className="account-chip"><span>{(user?.name||'L').slice(0,1).toUpperCase()}</span><div><b>{user?.name||'Learner'}</b><small>{user?.targetRole||'Target role not set'}</small></div></Link></div></div>
  </header>
  <main id="main-content" className="product-main">{children}</main>
  {more&&<div className="mobile-more-menu"><Link href="/settings">Settings</Link><Link href="/github">GitHub</Link><Link href="/interview">AI Interviewer</Link></div>}
  <PersistentAIWidget/>
 </div>
}
export default function AppShell({children}:{children:React.ReactNode}){return <RequireAuth><ShellInner>{children}</ShellInner></RequireAuth>}
