"use client";
import {useEffect,useRef,useState} from 'react';import {Bot,Expand,Minimize2,Send,X,RotateCcw,Copy,Check} from 'lucide-react';import {api} from '../lib/api';import {runPuter} from '../lib/ai';import {useApp} from './AppProvider';
type Msg={role:'user'|'ai';text:string};
function AIAnswer({text}:{text:string}){const blocks=text.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);return <div className="ai-answer">{(blocks.length?blocks:[text]).map((block,i)=>{const lines=block.split('\n').map(x=>x.trim()).filter(Boolean);const bullets=lines.length>1&&lines.every(x=>/^[-*•]\s+/.test(x));return bullets?<ul key={i}>{lines.map((x,j)=><li key={j}>{x.replace(/^[-*•]\s+/,'')}</li>)}</ul>:<p key={i}>{block}</p>})}</div>}
export default function PersistentAIWidget(){const{user,language}=useApp();const[open,setOpen]=useState(false),[full,setFull]=useState(false),[input,setInput]=useState(''),[sending,setSending]=useState(false),[provider,setProvider]=useState('puter'),[model,setModel]=useState('openai/gpt-oss-20b'),[models,setModels]=useState<any[]>([]),[msgs,setMsgs]=useState<Msg[]>([]),[copied,setCopied]=useState<number|null>(null);const trigger=useRef<HTMLButtonElement>(null);const box=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(open)api<any>('/api/v1/ai/history').then(r=>setMsgs(r.items||[])).catch(()=>{});},[open]);useEffect(()=>{if(open)api<any>(`/api/v1/ai/models?provider=${provider}`).then(r=>setModels(r.models||[])).catch(()=>setModels([]))},[open,provider]);
 useEffect(()=>{if(!full)return;const esc=(e:KeyboardEvent)=>{if(e.key==='Escape')exitFullscreen()};document.addEventListener('keydown',esc);document.body.classList.add('ai-fullscreen-active');setTimeout(()=>box.current?.querySelector('textarea')?.focus(),0);return()=>{document.removeEventListener('keydown',esc);document.body.classList.remove('ai-fullscreen-active')}},[full]);
 async function enterFullscreen(){const el=box.current;if(!el)return;try{if(el.requestFullscreen)await el.requestFullscreen();setFull(true)}catch{setFull(true)}}
 async function exitFullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen()}catch{}setFull(false);setTimeout(()=>trigger.current?.focus(),0)}
 useEffect(()=>{const onChange=()=>setFull(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',onChange);return()=>document.removeEventListener('fullscreenchange',onChange)},[]);
 async function push(m:Msg){setMsgs(x=>[...x,m]);await api('/api/v1/ai/history',{method:'POST',body:JSON.stringify({item:m})}).catch(()=>{})}
 async function send(){const q=input.trim();if(!q||sending)return;setInput('');await push({role:'user',text:q});setSending(true);try{const r=await api<any>('/api/v1/ai/ask',{method:'POST',body:JSON.stringify({question:q,context:window.location.pathname,language,provider,model,role:user?.targetRole||'',goal:'Build credible competency evidence'})});if(r.mode==='puter-client'){const prompt=r.prompt||q;const text=await runPuter(prompt,r.model||model);await push({role:'ai',text})}else await push({role:'ai',text:r.answer||'Evaluation unavailable — the selected provider returned no answer.'})}catch(e:any){await push({role:'ai',text:`Evaluation unavailable — ${e.message||'the selected provider failed'}.`})}finally{setSending(false)}}
 if(!user)return null;const content=<div ref={box} className={`ai-window ${full?'ai-window-full':''}`}><div className="ai-head"><div><b>SKILLSETRA Coach</b><small>Context-aware · evidence-aware · explicit provider</small></div><div className="ai-head-actions"><button onClick={()=>setMsgs([])} title="Clear local view"><RotateCcw/></button><button onClick={full?exitFullscreen:enterFullscreen} title={full?'Exit fullscreen':'Enter fullscreen'}>{full?<Minimize2/>:<Expand/>}</button><button onClick={()=>{setOpen(false);if(full)exitFullscreen()}} title="Close"><X/></button></div></div><div className="ai-toolbar"><select value={provider} onChange={e=>setProvider(e.target.value)}><option value="puter">Puter AI · Primary</option><option value="ollama">Ollama · Secondary</option></select><select value={model} onChange={e=>setModel(e.target.value)}>{(models.length?models:[{id:model,label:model}]).map((m:any)=><option key={m.id} value={m.id}>{m.label||m.id}</option>)}</select></div><div className="ai-messages">{msgs.length===0&&<div className="ai-welcome"><div className="ai-orb"><Bot/></div><h3>What do you want to prove?</h3><p>Ask about a gap, assessment, challenge, project, GitHub repository or learning step.</p></div>}{msgs.map((m,i)=><div className={`chat-msg ${m.role}`} key={`${i}-${m.text.slice(0,10)}`}><span>{m.role==='ai'?<Bot/>:<span className="avatar">{user.name[0]}</span>}</span><div className="chat-content">{m.role==='ai'?<AIAnswer text={m.text}/>:<p>{m.text}</p>}{m.role==='ai'&&<button className="ai-copy" onClick={()=>{navigator.clipboard?.writeText(m.text);setCopied(i);window.setTimeout(()=>setCopied(null),1400)}} title="Copy answer"><>{copied===i?<Check size={12}/>:<Copy size={12}/>} {copied===i?'Copied':'Copy'}</></button>}</div></div>)}{sending&&<div className="chat-msg ai"><Bot/><p>Waiting for the selected provider…</p></div>}</div><div className="ai-compose"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask your AI coach…"/><button onClick={send} disabled={sending||!input.trim()} aria-label="Send"><Send/></button></div></div>;
 return <>{!open&&<button ref={trigger} className="ai-fab" onClick={()=>setOpen(true)}><Bot/><span>AI Coach</span></button>}{open&&<div className={full?'ai-fullscreen-wrap':'ai-popover'}>{content}</div>}</>}
