-- SKILLSETRA production data model. Run after 001_initial.sql and 002_assessment_and_market.sql.
create extension if not exists pgcrypto;

create table if not exists workspaces(id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete cascade,name text not null default 'SKILLSETRA Workspace',created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists workspace_members(workspace_id uuid references workspaces(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,role text not null default 'member',created_at timestamptz default now(),primary key(workspace_id,user_id));
create table if not exists target_profiles(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,workspace_id uuid references workspaces(id) on delete cascade,target_role text,target_level text,career_goal text,timeline text,experience text,weekly_learning_hours numeric,preferred_language text,learning_preferences jsonb default '{}',constraints jsonb default '{}',location text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists role_competencies_v2(id uuid primary key default gen_random_uuid(),role text not null,competency text not null,importance int default 1,created_at timestamptz default now(),unique(role,competency));
create table if not exists assessment_versions(id uuid primary key default gen_random_uuid(),assessment_id uuid references assessments(id) on delete cascade,version int not null,metadata jsonb default '{}',created_at timestamptz default now(),unique(assessment_id,version));
create table if not exists assessment_options(id uuid primary key default gen_random_uuid(),question_id uuid references assessment_questions(id) on delete cascade,label text not null,position int not null,is_correct boolean default false,explanation text);
create table if not exists assessment_results(id uuid primary key default gen_random_uuid(),attempt_id uuid references assessment_attempts(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,score_percent int,passed boolean,summary text,next_step text,created_at timestamptz default now());
create table if not exists assessment_dimension_scores(id uuid primary key default gen_random_uuid(),result_id uuid references assessment_results(id) on delete cascade,dimension text,score numeric,evidence_count int default 0); 
create table if not exists assessment_ai_interpretations(id uuid primary key default gen_random_uuid(),result_id uuid references assessment_results(id) on delete cascade,provider text,model text,observed jsonb,inferred jsonb,recommendations jsonb,created_at timestamptz default now());
create table if not exists challenge_versions(id uuid primary key default gen_random_uuid(),challenge_id uuid references challenges(id) on delete cascade,version int not null,payload jsonb not null,created_at timestamptz default now(),unique(challenge_id,version));
create table if not exists challenge_answers(id uuid primary key default gen_random_uuid(),attempt_id uuid references challenge_attempts(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,answer text,created_at timestamptz default now());
create table if not exists challenge_test_cases(id uuid primary key default gen_random_uuid(),challenge_id uuid references challenges(id) on delete cascade,input jsonb,expected jsonb,visibility text default 'public');
create table if not exists challenge_execution_results(id uuid primary key default gen_random_uuid(),attempt_id uuid references challenge_attempts(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,status text,passed_tests int,total_tests int,execution_ms int,memory_kb int,stderr text,created_at timestamptz default now());
create table if not exists challenge_evaluations_v2(id uuid primary key default gen_random_uuid(),attempt_id uuid references challenge_attempts(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,provider text,model text,observed jsonb,inferred jsonb,missing jsonb,next_steps jsonb,available boolean default true,created_at timestamptz default now());
create table if not exists project_evidence(id uuid primary key default gen_random_uuid(),project_id uuid references projects(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,source_type text,source_ref text,summary text,confidence text,created_at timestamptz default now());
create table if not exists project_defense_questions(id uuid primary key default gen_random_uuid(),session_id uuid references project_defense_sessions(id) on delete cascade,position int,question text,context jsonb default '{}');
create table if not exists project_defense_answers(id uuid primary key default gen_random_uuid(),session_id uuid references project_defense_sessions(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,question_id uuid references project_defense_questions(id),answer text,provider text,model text,evaluation jsonb,created_at timestamptz default now());
create table if not exists github_repository_analysis(id uuid primary key default gen_random_uuid(),repository_id uuid references github_repositories(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,analysis_version int default 1,observed jsonb,inferred jsonb,recommended jsonb,provider text,model text,created_at timestamptz default now());
create table if not exists github_evidence(id uuid primary key default gen_random_uuid(),repository_id uuid references github_repositories(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,claim text,evidence jsonb,confidence text,created_at timestamptz default now());
create table if not exists evidence_sources(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,source_type text,source_url text,source_label text,metadata jsonb default '{}',created_at timestamptz default now());
create table if not exists evidence_events(id uuid primary key default gen_random_uuid(),evidence_id uuid references evidence(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,event_type text,payload jsonb,created_at timestamptz default now());
create table if not exists evidence_verifications(id uuid primary key default gen_random_uuid(),evidence_id uuid references evidence(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,method text,status text,verified_at timestamptz,notes text);
create table if not exists subjects(id uuid primary key default gen_random_uuid(),slug text unique,name text not null,overview text,prerequisites jsonb default '[]',created_at timestamptz default now());
create table if not exists learning_paths(id uuid primary key default gen_random_uuid(),subject_id uuid references subjects(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,title text,description text,level text,status text default 'not_started',created_at timestamptz default now());
create table if not exists learning_modules(id uuid primary key default gen_random_uuid(),learning_path_id uuid references learning_paths(id) on delete cascade,title text,position int,description text);
create table if not exists learning_resources(id uuid primary key default gen_random_uuid(),subject_id uuid references subjects(id),title text not null,url text,kind text,level text,provider text,verified boolean default false,metadata jsonb default '{}',created_at timestamptz default now());
create table if not exists learning_resource_progress(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,resource_id uuid references learning_resources(id) on delete cascade,status text default 'not_started',progress numeric default 0,completed_at timestamptz,updated_at timestamptz default now(),unique(user_id,resource_id));
create table if not exists completed_resources(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,resource_id uuid references learning_resources(id) on delete cascade,completed_at timestamptz default now(),unique(user_id,resource_id));
create table if not exists subject_progress(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,subject_id uuid references subjects(id) on delete cascade,status text default 'not_started',progress numeric default 0,updated_at timestamptz default now(),unique(user_id,subject_id));
create table if not exists roadmaps(id uuid primary key default gen_random_uuid(),user_id uuid unique references auth.users(id) on delete cascade,target_role text,target_level text,goal text,title text,description text,version int default 1,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists roadmap_versions(id uuid primary key default gen_random_uuid(),roadmap_id uuid references roadmaps(id) on delete cascade,version int,reason text,payload jsonb,created_at timestamptz default now());
create table if not exists roadmap_steps(id uuid primary key default gen_random_uuid(),roadmap_id uuid references roadmaps(id) on delete cascade,step_order int,title text,objective text,why text,status text default 'upcoming',next_action text,skills jsonb default '[]');
create table if not exists roadmap_step_materials(id uuid primary key default gen_random_uuid(),step_id uuid references roadmap_steps(id) on delete cascade,resource_id uuid references learning_resources(id) on delete cascade);
create table if not exists roadmap_step_completions(id uuid primary key default gen_random_uuid(),step_id uuid references roadmap_steps(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,completed_at timestamptz default now(),unique(step_id,user_id));
create table if not exists notifications_v2(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,title text,body text,kind text,read boolean default false,created_at timestamptz default now());
create table if not exists notification_preferences(user_id uuid primary key references auth.users(id) on delete cascade,assessment boolean default true,evidence boolean default true,roadmap boolean default true,github boolean default true,learning boolean default true,updated_at timestamptz default now());
create table if not exists audit_logs(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,action text,resource_type text,resource_id text,metadata jsonb default '{}',created_at timestamptz default now());
create table if not exists user_settings_v2(user_id uuid primary key references auth.users(id) on delete cascade,ai_provider text default 'puter',ai_model text,appearance text default 'dark',language text default 'English',timezone text,location text,updated_at timestamptz default now());
create table if not exists ai_conversations(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,title text,created_at timestamptz default now(),updated_at timestamptz default now());
create table if not exists ai_messages(id uuid primary key default gen_random_uuid(),conversation_id uuid references ai_conversations(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,role text,content text,created_at timestamptz default now());
create table if not exists ai_requests(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,request_id text,provider text,model text,task_type text,latency_ms int,success boolean,error_code text,created_at timestamptz default now());
create table if not exists ai_evaluations(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,source_type text,source_id text,provider text,model text,observed jsonb,inferred jsonb,recommendations jsonb,created_at timestamptz default now());
create table if not exists workspace_snapshots(user_id uuid primary key references auth.users(id) on delete cascade,data jsonb not null default '{}',updated_at timestamptz default now());

-- RLS helper: every table with user_id is isolated to the current authenticated user.
DO $$ declare t text; begin
 for t in select unnest(array['target_profiles','assessment_results','assessment_ai_interpretations','challenge_answers','challenge_execution_results','challenge_evaluations_v2','project_evidence','project_defense_answers','github_repository_analysis','github_evidence','evidence_sources','evidence_events','evidence_verifications','learning_paths','learning_resource_progress','completed_resources','subject_progress','roadmaps','roadmap_step_completions','notifications_v2','audit_logs','ai_conversations','ai_messages','ai_requests','ai_evaluations','workspace_snapshots']) loop
  execute format('alter table %I enable row level security',t);
  execute format('drop policy if exists %I_user_isolation on %I',t,t);
  execute format('create policy %I_user_isolation on %I for all using (user_id = auth.uid()) with check (user_id = auth.uid())',t,t);
 end loop;
end $$;

alter table workspaces enable row level security;
DO $$ BEGIN
 if not exists(select 1 from pg_policies where schemaname=current_schema() and tablename='workspaces' and policyname='workspaces_owner') then create policy workspaces_owner on workspaces for all using(owner_id=auth.uid()) with check(owner_id=auth.uid()); end if;
END $$;
alter table workspace_members enable row level security;
DO $$ BEGIN
 if not exists(select 1 from pg_policies where schemaname=current_schema() and tablename='workspace_members' and policyname='workspace_member_self') then create policy workspace_member_self on workspace_members for select using(user_id=auth.uid() or workspace_id in(select id from workspaces where owner_id=auth.uid())); end if;
END $$;
create index if not exists workspace_snapshots_updated_idx on workspace_snapshots(updated_at desc);
create index if not exists learning_progress_user_idx on learning_resource_progress(user_id,updated_at desc);
create index if not exists ai_requests_user_idx on ai_requests(user_id,created_at desc);

-- Child-table policies: ownership is inherited from the user-owned parent.
ALTER TABLE assessment_dimension_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE roadmap_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE roadmap_steps ENABLE ROW LEVEL SECURITY;
ALTER TABLE roadmap_step_materials ENABLE ROW LEVEL SECURITY;
ALTER TABLE project_defense_questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE learning_modules ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
 if not exists(select 1 from pg_policies where tablename='assessment_dimension_scores' and policyname='assessment_dimension_owner') then create policy assessment_dimension_owner on assessment_dimension_scores for all using(exists(select 1 from assessment_results r where r.id=assessment_dimension_scores.result_id and r.user_id=auth.uid())) with check(exists(select 1 from assessment_results r where r.id=assessment_dimension_scores.result_id and r.user_id=auth.uid())); end if;
 if not exists(select 1 from pg_policies where tablename='roadmap_versions' and policyname='roadmap_versions_owner') then create policy roadmap_versions_owner on roadmap_versions for all using(exists(select 1 from roadmaps r where r.id=roadmap_versions.roadmap_id and r.user_id=auth.uid())) with check(exists(select 1 from roadmaps r where r.id=roadmap_versions.roadmap_id and r.user_id=auth.uid())); end if;
 if not exists(select 1 from pg_policies where tablename='roadmap_steps' and policyname='roadmap_steps_owner_v2') then create policy roadmap_steps_owner_v2 on roadmap_steps for all using(exists(select 1 from roadmaps r where r.id=roadmap_steps.roadmap_id and r.user_id=auth.uid())) with check(exists(select 1 from roadmaps r where r.id=roadmap_steps.roadmap_id and r.user_id=auth.uid())); end if;
 if not exists(select 1 from pg_policies where tablename='roadmap_step_materials' and policyname='roadmap_material_owner') then create policy roadmap_material_owner on roadmap_step_materials for all using(exists(select 1 from roadmap_steps s join roadmaps r on r.id=s.roadmap_id where s.id=roadmap_step_materials.step_id and r.user_id=auth.uid())) with check(exists(select 1 from roadmap_steps s join roadmaps r on r.id=s.roadmap_id where s.id=roadmap_step_materials.step_id and r.user_id=auth.uid())); end if;
 if not exists(select 1 from pg_policies where tablename='project_defense_questions' and policyname='defense_questions_owner') then create policy defense_questions_owner on project_defense_questions for all using(exists(select 1 from project_defense_sessions s where s.id=project_defense_questions.session_id and s.user_id=auth.uid())) with check(exists(select 1 from project_defense_sessions s where s.id=project_defense_questions.session_id and s.user_id=auth.uid())); end if;
 if not exists(select 1 from pg_policies where tablename='learning_resources' and policyname='learning_resources_public_read') then create policy learning_resources_public_read on learning_resources for select using(true); end if;
 if not exists(select 1 from pg_policies where tablename='learning_modules' and policyname='learning_modules_public_read') then create policy learning_modules_public_read on learning_modules for select using(true); end if;
END $$;
