import PublicPage from "../../components/PublicPage";

const sections=[
 ["01","Using the product","SKILLsetra provides a competency evidence workspace for learning, practice, project analysis, interview preparation and related activities. It is not a professional certification authority and does not guarantee employment, admission, compensation or other outcomes."],
 ["02","Your content","You remain responsible for content you submit, including code, documents, repository links, project descriptions and claims. You should have the rights and permissions necessary to submit and analyze that content."],
 ["03","Evidence integrity","Do not present copied, fabricated, generated or third-party work as independently completed evidence. A self-declared claim is intentionally distinct from observed evidence in the product."],
 ["04","AI-assisted features","AI-generated answers, analyses, feedback and recommendations may be incomplete, incorrect or unavailable. Review important technical, security, academic, legal and career decisions independently before acting on them."],
 ["05","Acceptable use","Do not use the application to bypass access controls, attack systems, distribute malware, steal credentials, impersonate people, fabricate evidence, violate third-party rights or otherwise break applicable law."],
 ["06","Integrations","When you connect GitHub or another external service, you authorize the application only for the functionality you choose. Use least-privilege credentials and revoke access when it is no longer required."],
 ["07","Availability","The current application is a hackathon/demo-oriented build. Features, integrations, AI providers, model availability, resource links and storage behavior can change without preserving every demo behavior."],
 ["08","Third-party services","External services have separate terms, privacy rules and availability. Your use of an external provider through SKILLsetra remains subject to that provider's applicable rules."],
 ["09","No professional advice","AI output and product analytics are not a substitute for qualified legal, medical, financial, security, academic or other professional advice. Use appropriate human review for consequential decisions."],
 ["10","Account and security","Keep account credentials and tokens confidential. Notify the deployment operator if you believe an account or integration has been compromised. Do not place secrets in evidence, project descriptions or chat prompts."],
 ["11","Changes","The operator may update these terms as the product evolves. The current version and review date are shown on this page. Continued use after an update is subject to the applicable version for the deployment."],
 ["12","Questions","For questions about these terms or a specific deployment, use the Contact page. Production or institutional deployments should obtain appropriate legal, privacy, security and accessibility review for their jurisdiction."]
];
export default function Terms(){return <PublicPage eyebrow="Terms of use" title="Clear rules for using SKILLsetra responsibly."><div className="legal-intro"><p>These terms describe the intended use of the current SKILLsetra application. They are written for the demo/application context and should be replaced or supplemented by deployment-specific legal terms before commercial or institutional launch.</p><div className="legal-meta"><span>Last reviewed: 1 October 2026</span><span>Current demo/application terms</span></div></div><div className="legal-list">{sections.map(([n,h,p])=><section className="legal-section" key={n}><div className="legal-number">{n}</div><div><h2>{h}</h2><p>{p}</p></div></section>)}</div><aside className="legal-callout"><b>Deployment note</b><span>Before public/commercial deployment, replace demo wording with the operator's actual legal entity, contact channel, retention details and jurisdiction-specific terms.</span></aside><aside className="legal-callout"><b>Responsible use matters.</b><span>Keep evidence truthful, protect credentials and treat AI output as assistance that requires appropriate review.</span></aside></PublicPage>}
