"use client";
import {useEffect,useState} from "react";
import {ArrowRight,MessageSquare,ShieldCheck} from "lucide-react";
import Link from "next/link";
import AppLayout from "../../../components/AppLayout";import AIControls from "../../../components/AIControls";
import {api} from "../../../lib/api";
import {runPuter} from "../../../lib/ai";

export default function Defense(){
 const [d,setD]=useState<any>();const [i,setI]=useState(0);const [answer,setAnswer]=useState("");const [result,setResult]=useState<any>();const [loading,setLoading]=useState(false);const [provider,setProvider]=useState("puter");const [model,setModel]=useState("openai/gpt-oss-20b");
 useEffect(()=>{api("/api/v1/project-defense").then(setD).catch(()=>setD({questions:['Project defense service unavailable. Start the API and refresh to load the questions.']}))},[]);
 async function submit(){if(!d?.project_id||!d?.questions?.[i]||!answer.trim())return;setLoading(true);try{const r=await api<any>("/api/v1/project-defense",{method:"POST",body:JSON.stringify({project_id:d.project_id,question:d.questions[i],answer,provider,model,language:"English"})});if(r.provider==="puter"){r.ai_note=await runPuter(`Evaluate this project defense answer for reasoning, evidence and uncertainty. Respond in English. Question: ${d.questions[i]}. Answer: ${answer}`,model)}setResult(r)}finally{setLoading(false)}}
 return <AppLayout><main className="container page-container"><div className="page-title-row"><div><div className="eyebrow">Project defense</div><h1>Defend the decisions behind what you built.</h1><p>SKILLSETRA tests reasoning, trade-offs, adaptation and failure thinking through questions that change context.</p></div><Link className="btn ghost" href="/projects">Back to project <ArrowRight size={15}/></Link></div><div className="challenge-layout"><section className="panel"><div className="eyebrow">Question {i+1} / {d?.questions?.length||5}</div><h2 className="defense-question">{d?.questions?.[i]}</h2><div className="mini-callout"><ShieldCheck size={16}/><span>There is no single “correct” architecture. Your reasoning and evidence matter.</span></div></section><section className="panel"><div className="panel-head"><div><div className="eyebrow">Your defense</div><h2>Explain your decision</h2></div><MessageSquare size={18}/></div><AIControls provider={provider} model={model} onProvider={setProvider} onModel={setModel}/><textarea className="big-textarea" value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Explain the decision, trade-off, alternative you rejected, and how you would verify it…"/><div className="row-actions" style={{marginTop:12}}><button className="btn primary" onClick={submit} disabled={loading||!answer.trim()}>{loading?"Evaluating…":"Submit defense"} <ArrowRight size={15}/></button></div>{result&&<div className="evaluation-card"><span className="eyebrow">Evidence created · {result.mode}</span><h3>{result.status}</h3><p>{result.observed}</p><p className="muted"><b>Next:</b> {result.next_step}</p><button className="btn small" onClick={()=>{setI(Math.min(i+1,(d?.questions?.length||1)-1));setAnswer("");setResult(null)}}>Next defense question <ArrowRight size={13}/></button></div>}</section></div></main></AppLayout>
}
