"use client";
import {useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import AppLayout from "../../components/AppLayout";import {useApp} from "../../components/AppProvider";
import {api} from "../../lib/api";
import {ArrowLeft,ArrowRight,CheckCircle2,Target,BrainCircuit,BookOpen,FileCheck2} from "lucide-react";

type Q={id:string;competency:string;difficulty:string;question:string;options:string[]};
const roles=["ML Engineer","AI Engineer","Data Scientist","Data Analyst","Backend Developer","Full-Stack Developer","Frontend Developer","Python Developer","DevOps Engineer","Cybersecurity"];

export default function Onboarding(){
 const router=useRouter();const {setTargetRole}=useApp();
 const [step,setStep]=useState(1),[role,setRole]=useState(""),[experience,setExperience]=useState("Early career"),[goal,setGoal]=useState("Become job-ready with credible evidence"),[questions,setQuestions]=useState<Q[]>([]),[answers,setAnswers]=useState<Record<string,string>>({}),[result,setResult]=useState<any>(null),[resources,setResources]=useState<any[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(step===2&&!questions.length)loadQuestions()},[step]);
 async function saveGoal(){if(!role){setError("Choose a target role first.");return}setError("");setLoading(true);try{await api("/api/profile/goal",{method:"POST",body:JSON.stringify({target_role:role,experience,goal})});setTargetRole(role);setStep(2)}catch(e:any){setError(e.message||"Could not save your target role.")}finally{setLoading(false)}}
 async function loadQuestions(){setLoading(true);setError("");try{const r=await api<any>("/api/assessment");setQuestions(r.questions||[])}catch(e:any){setError(e.message||"Could not load the baseline questions.")}finally{setLoading(false)}}
 async function submitAssessment(){const unanswered=questions.filter(q=>answers[q.id]===undefined);if(unanswered.length){setError(`Please answer all ${unanswered.length} remaining question${unanswered.length===1?"":"s"}.`);return}setLoading(true);setError("");try{const r=await api<any>("/api/assessment/submit",{method:"POST",body:JSON.stringify({assessment_id:"adaptive-v1",answers})});setResult(r);const rr=await api<any>("/api/resources");setResources(rr.items||[]);setStep(3)}catch(e:any){setError(e.message||"Assessment could not be submitted.")}finally{setLoading(false)}}
 const gaps=result?.details?.filter((x:any)=>!x.is_correct).map((x:any)=>x.competency).filter((x:string,i:number,a:string[])=>a.indexOf(x)===i).slice(0,6)||[];
 return <AppLayout><div className="page onboarding-page">
  <div className="page-head"><div><div className="eyebrow">FIRST SESSION · EVIDENCE BASELINE</div><h1>Start with what you want to prove.</h1><p>SKILLSETRA does not drop you into a pre-filled dashboard. Choose a target, answer applied questions, then see your competency baseline, gaps and next evidence actions.</p></div></div>
  <div className="onboarding-steps"><span className={step>=1?"active":""}>01 Target role</span><span className={step>=2?"active":""}>02 Evidence questions</span><span className={step>=3?"active":""}>03 Gap + next actions</span></div>
  {error&&<div className="notice error" role="alert">{error}</div>}
  {step===1&&<section className="onboard-card panel"><div className="onboard-intro"><div className="onboard-icon"><Target/></div><div><div className="eyebrow">TARGET ROLE</div><h2>What role are you preparing for?</h2><p>This target becomes the reference point for your evidence requirements and learning recommendations.</p></div></div><div className="role-grid">{roles.map(r=><button type="button" className={`role-choice ${role===r?"selected":""}`} key={r} onClick={()=>setRole(r)}><b>{r}</b><small>Use this as your competency target</small></button>)}</div><div className="form-grid onboarding-fields"><div className="field"><label>EXPERIENCE LEVEL</label><select value={experience} onChange={e=>setExperience(e.target.value)}><option>Early career</option><option>Intermediate</option><option>Experienced</option></select></div><div className="field"><label>PRIMARY GOAL</label><input value={goal} onChange={e=>setGoal(e.target.value)}/></div></div><div className="action-row"><button className="button primary" disabled={!role||loading} onClick={saveGoal}>{loading?"Saving target…":"Continue to evidence questions"}<ArrowRight size={15}/></button></div></section>}
  {step===2&&<section className="panel"><div className="onboard-intro"><div className="onboard-icon"><BrainCircuit/></div><div><div className="eyebrow">EVIDENCE QUESTIONS · {role.toUpperCase()}</div><h2>Show what you can actually do.</h2><p>Answer the applied questions honestly. Your answers become baseline evidence; they are not a claim that you are job-ready.</p></div></div>{loading&&!questions.length?<div className="empty">Preparing your baseline questions…</div>:<div className="question-stack">{questions.map((q,i)=><article className="question-card" key={q.id}><div className="question-meta"><span>Q{i+1}</span><span>{q.competency}</span><span>{q.difficulty}</span></div><h3>{q.question}</h3><div className="option-grid">{q.options.map((o,j)=><button type="button" className={answers[q.id]===String(j)?"option selected":"option"} key={o} onClick={()=>setAnswers(a=>({...a,[q.id]:String(j)}))}><span>{String.fromCharCode(65+j)}</span>{o}</button>)}</div></article>)}</div>}<div className="action-row"><button className="button" onClick={()=>setStep(1)}><ArrowLeft size={15}/> Change target</button><button className="button primary" disabled={loading||!questions.length} onClick={submitAssessment}>{loading?"Analyzing evidence…":"Analyze my baseline"}<ArrowRight size={15}/></button></div></section>}
  {step===3&&<>
   <section className="grid grid-3"><article className="metric-card onboarding-result"><span className="eyebrow">OVERALL COMPETENCY BASELINE</span><strong>{result?.score||0}%</strong><small>{result?.correct||0} of {result?.total||0} applied questions answered correctly</small></article><article className="metric-card"><span className="eyebrow">GAPS DETECTED</span><strong>{gaps.length}</strong><small>Competency areas needing more evidence</small></article><article className="metric-card"><span className="eyebrow">TARGET</span><strong style={{fontSize:22}}>{role}</strong><small>Your roadmap is anchored to this role</small></article></section>
   <div className="grid grid-2" style={{marginTop:16}}><section className="panel"><div className="panel-head"><div><div className="eyebrow">GAP MAP</div><h2>What to strengthen next</h2></div><FileCheck2/></div>{gaps.length?<div className="gap-list">{gaps.map((g:string)=><div className="signal warn" key={g}><b>{g}</b><span>Build a concrete artifact, practice in a changed context, then re-test.</span></div>)}</div>:<div className="signal good"><b>No incorrect areas in this baseline</b><span>Continue by creating target evidence through projects, challenges and GitHub.</span></div>}<div className="action-row"><button className="button primary" onClick={()=>router.push("/evidence")}>Open Claim Evidence <FileCheck2 size={14}/></button><button className="button" onClick={()=>router.push("/assessment")}>Full assessment <ArrowRight size={14}/></button></div></section>
   <section className="panel"><div className="panel-head"><div><div className="eyebrow">LEARNING MATERIALS</div><h2>Start closing the gap</h2></div><BookOpen/></div><p className="muted">These resources are the starting catalog. Use them alongside projects and re-validation so learning produces evidence.</p><div className="resource-list">{resources.slice(0,6).map((r:any)=><article className="resource" key={r.id}><span className="tag blue">{String(r.type||"RESOURCE").toUpperCase()}</span><h3>{r.title}</h3><p>{r.description}</p><a href={r.url} target="_blank" rel="noreferrer">Open material ↗</a></article>)}</div></section></div>
   <section className="panel onboarding-next"><div><div className="eyebrow">YOUR NEXT LOOP</div><h2>Claim → practice → prove → re-test</h2><p>Now that SKILLSETRA has a baseline, use Claim Evidence to connect your strongest artifacts, then use Challenges, Projects, GitHub and the Roadmap to create stronger evidence for <b>{role}</b>.</p></div><div className="action-row"><button className="button" onClick={()=>router.push("/roadmap")}>Open roadmap <ArrowRight size={14}/></button><button className="button" onClick={()=>router.push("/learn")}>Explore learning <BookOpen size={14}/></button></div></section>
  </>}
 </div></AppLayout>
}
