"use client";
import {useState} from "react";
import AppLayout from "../../components/AppLayout";
import AIControls from "../../components/AIControls";
import {api} from "../../lib/api";
import {runPuter} from "../../lib/ai";
import {ScanSearch,ArrowRight,Copy,Check} from "lucide-react";
function blocks(text:string){const labels=["FACTS","IMPLICATIONS","AMBIGUITIES","ASSUMPTIONS","RISKS","TERMINOLOGY","ACTIONS"];const out:any[]=[];let current:any=null;for(const line of text.split(/\r?\n/)){const clean=line.trim();const label=labels.find(x=>clean.toUpperCase().startsWith(x));if(label){current={label,text:""};out.push(current);const rest=clean.slice(label.length).replace(/^[:\-\s]+/,"");if(rest)current.text=rest}else if(current){current.text+=(current.text?"\n":"")+clean}}return out.length?out:[{label:"STRUCTURED INTERPRETATION",text}];}
export default function Interpret(){const [source,setSource]=useState("");const [out,setOut]=useState("");const [busy,setBusy]=useState(false);const [provider,setProvider]=useState("puter");const [model,setModel]=useState("openai/gpt-oss-20b");const [copied,setCopied]=useState(false);async function go(){if(!source.trim())return;setBusy(true);try{const r=await api<any>("/api/v1/interpret/analyze",{method:"POST",body:JSON.stringify({source,provider,model,language:"English"})});setOut(r.mode==="puter-client"?await runPuter(r.prompt,r.model||model):(r.analysis||r.notice||""))}catch(e:any){setOut(e.message||"Interpretation could not be completed.")}finally{setBusy(false)}}async function copy(){await navigator.clipboard?.writeText(out);setCopied(true);setTimeout(()=>setCopied(false),1200)}return <AppLayout><div className="page"><div className="page-head"><div><div className="eyebrow">Interpretation Engine</div><h1>Turn dense technical material into a decision map.</h1><p>Paste requirements, error messages, architecture notes, documentation or an interview prompt. SKILLSETRA separates facts from inference and uncertainty.</p></div></div><div className="grid grid-2"><section className="panel"><div className="panel-head"><h2>Input</h2><ScanSearch/></div><textarea className="large-editor" value={source} onChange={e=>setSource(e.target.value)} placeholder="Paste technical material here…"/><AIControls provider={provider} model={model} onProvider={setProvider} onModel={setModel}/><button className="button primary" style={{marginTop:12}} onClick={go} disabled={busy||!source.trim()}>{busy?"Interpreting…":<>Interpret <ArrowRight size={14}/></>}</button></section><section className="panel"><div className="panel-head"><div><div className="eyebrow">Structured interpretation</div><h2>AI answer map</h2></div><ScanSearch/></div>{out?<><div className="answer-toolbar"><button className="button" onClick={copy}>{copied?<Check size={13}/>:<Copy size={13}/>} {copied?"Copied":"Copy answer"}</button></div><div className="structured-answer">{blocks(out).map((b:any,i:number)=><article className={`structured-block ${i===0?"highlight":""}`} key={i}><h3>{b.label}</h3><p>{b.text||"No detail returned."}</p></article>)}</div></>:<div className="empty">FACTS · IMPLICATIONS · AMBIGUITIES · ASSUMPTIONS · RISKS · TERMINOLOGY · ACTIONS</div>}</section></div></div></AppLayout>}
