"use client";
import React,{useEffect,useMemo,useState} from 'react';
import {ArrowRight,CheckCircle2,Clock3,Target,TrendingUp,BookOpen,FolderKanban,ShieldCheck,Route,AlertTriangle,FileCheck2} from 'lucide-react';
import {api} from '../../../../lib/api';
import type {ScreenId} from '../../types';
interface DashboardData{goal_progress?:number;learner:{name?:string;target_role?:string;primary_goal?:string};summary:Record<string,number>;competencies:Array<{name:string;status:string;evidence:number;level:string}>;evidence:Array<{id:string;activity:string;competency:string;evidence:string;result:string;confidence:string;date:string}>;career:{role:string;gaps:string[];strong?:string[];developing?:string[]};next:{title:string;reason:string;href:string};evidence_claims?:any[];trend?:any[]}
export const Dashboard:React.FC<{onNavigate:(s:ScreenId)=>void}>=({onNavigate})=>{
 const[d,setD]=useState<DashboardData|null>(null);const[a,setA]=useState<any>(null);const[loading,setLoading]=useState(true);
 useEffect(()=>{
   let alive=true;
   (async()=>{
     try{
       const x=await api<DashboardData>('/api/v1/dashboard');
       if(!alive)return;
       setD(x);
       try{setA(await api('/api/v1/analytics'))}catch{setA(null)}
     }catch(err:any){
       if(alive)setD(null);
     }finally{if(alive)setLoading(false)}
   })();
   return()=>{alive=false};
 },[]);
 const readiness=useMemo(()=>{if(!d?.competencies?.length)return 0;return Math.round(d.competencies.reduce((sum,x)=>sum+Math.max(0,Math.min(100,x.evidence||0)),0)/d.competencies.length)},[d]);
 if(loading)return <div className="page"><div className="empty">Loading your evidence dashboard…</div></div>;
 if(!d)return <div className="page"><div className="empty">Dashboard data is unavailable. The demo backend may still be starting. Refresh in a few seconds or open the API health check.</div><div className="action-row" style={{marginTop:12}}><button className="button" onClick={()=>location.reload()}>Refresh dashboard</button><a className="button" href="/api/v1/health" target="_blank" rel="noreferrer">Check API health</a></div></div>;
 const name=d.learner?.name||'Learner'; const gaps=d.career?.gaps||[]; const avg=a?.assessment_scores?.length?Math.round(a.assessment_scores.reduce((s:number,x:any)=>s+x.score,0)/a.assessment_scores.length):null;
 return <div className="page space-y-6">
  <section className="page-head"><div><div className="eyebrow">Evidence workspace</div><h1>Your competency cockpit.</h1><p>{name}, SKILLSETRA connects your target role to evidence, assessments, projects, learning and verification. A score never stands alone as proof.</p></div><div className="action-row"><button className="button" onClick={()=>location.href='/evidence'}><FileCheck2 size={14}/> Evidence</button><button className="button primary" onClick={()=>onNavigate('diagnostic')}>Assess the skill <ArrowRight size={15}/></button></div></section>
  <div className="grid grid-4"><Metric label="Goal progression" value={`${d.goal_progress??readiness}%`} icon={<ShieldCheck/>} sub="Against target-role competencies"/><Metric label="Strong evidence" value={d.summary.strong||0} icon={<CheckCircle2/>} sub="Current strong areas"/><Metric label="Needs evidence" value={d.summary.needs||0} icon={<Target/>} sub="Priority gaps"/><Metric label="Evidence events" value={d.evidence.length} icon={<Clock3/>} sub="Recorded workspace events"/></div>
  <section className="panel readiness-panel"><div className="panel-head"><div><div className="eyebrow">Role readiness map</div><h2>{d.learner.target_role||'Target role not set'}</h2></div><Route/></div><div className="readiness-grid"><div><div className="readiness-score"><strong>{readiness}%</strong><span>evidence coverage signal</span></div><div className="bar readiness-bar"><i style={{width:`${readiness}%`}}/></div><p className="muted">This is a workspace evidence signal, not a hiring prediction or certification.</p></div><div className="readiness-list"><div><b>Strong</b><span>{d.summary.strong||0} competencies</span></div><div><b>Developing</b><span>{d.summary.developing||0} competencies</span></div><div><b>Priority gaps</b><span>{gaps.slice(0,3).join(', ')||'None recorded'}</span></div></div></div></section>
  <div className="grid grid-2"><section className="panel"><div className="panel-head"><div><div className="eyebrow">Target</div><h2>{d.learner.target_role||'Target role not set'}</h2></div><Target/></div><p className="muted">{d.learner.primary_goal||'Set a concrete career goal to make the roadmap role-specific.'}</p><div className="action-row"><button className="button" onClick={()=>onNavigate('profile')}>Update target</button><button className="button" onClick={()=>onNavigate('roadmap')}>Open roadmap</button><button className="button" onClick={()=>location.href='/evidence'}>Target evidence</button></div></section><section className="panel"><div className="panel-head"><div><div className="eyebrow">Next best action</div><h2>{d.next.title}</h2></div><ArrowRight/></div><p className="muted">{d.next.reason}</p><div className="action-row"><button className="button primary" onClick={()=>location.href=d.next.href}>Practice now</button><button className="button" onClick={()=>location.href='/projects'}>Add project evidence</button></div></section></div>
  <div className="grid grid-2"><section className="panel"><div className="panel-head"><div><div className="eyebrow">Competency coverage</div><h2>Where evidence is strongest</h2></div><TrendingUp/></div><div className="bars">{d.competencies.slice(0,10).map(c=><div className="bar-row" key={c.name}><div><span>{c.name}</span><span>{Math.round(c.evidence||0)}%</span></div><div className="bar"><i style={{width:`${Math.max(0,Math.min(100,c.evidence||0))}%`}}/></div></div>)}</div></section><section className="panel"><div className="panel-head"><div><div className="eyebrow">Recent evidence</div><h2>Observed activity</h2></div><FolderKanban/></div>{d.evidence.length?d.evidence.slice(0,5).map(e=><div className="timeline-item" key={e.id}><div className="timeline-dot"><CheckCircle2 size={14}/></div><div><b>{e.activity} · {e.competency}</b><p>{e.evidence}</p><small>{e.date} · {e.confidence||'Unknown'} confidence · {e.result||'Observed'}</small></div></div>):<div className="empty">No evidence events yet. Complete an assessment, challenge, project or learning activity to start the loop.</div>}</section></div>
  <div className="grid grid-3"><section className="panel"><div className="panel-head"><div><div className="eyebrow">Claims</div><h2>Claim vs proof</h2></div><FileCheck2/></div><strong>{d.evidence_claims?.length||0}</strong><p className="muted">Self-declared claims stay separate from verified or observed evidence.</p><button className="button" onClick={()=>location.href='/evidence'}>Review evidence</button></section><section className="panel"><div className="panel-head"><div><div className="eyebrow">Assessment</div><h2>Recent validation</h2></div><CheckCircle2/></div><strong>{avg!==null?`${avg}%`:'—'}</strong><p className="muted">Average of recorded assessment attempts.</p><button className="button" onClick={()=>onNavigate('diagnostic')}>Retest</button></section><section className="panel"><div className="panel-head"><div><div className="eyebrow">Attention</div><h2>Keep the loop moving</h2></div><AlertTriangle/></div><strong>{gaps.length}</strong><p className="muted">Target-role competencies currently needing stronger evidence.</p><button className="button" onClick={()=>location.href='/roadmap'}>Open roadmap</button></section></div>
  <section className="panel"><div className="panel-head"><div><div className="eyebrow">Learning loop</div><h2>Learn → Practice → Prove → Retest</h2></div><BookOpen/></div><p className="muted">Learning completion is stored separately from competency evidence. Use a concrete artifact, assessment, challenge or project defense to create stronger proof.</p><div className="action-row"><button className="button" onClick={()=>onNavigate('roadmap')}>Continue journey</button><button className="button" onClick={()=>onNavigate('challenges')}>Open challenges</button><button className="button" onClick={()=>location.href='/analytics'}>View analytics</button></div></section>
 </div>
}
function Metric({label,value,icon,sub}:{label:string;value:string|number;icon:React.ReactNode;sub:string}){return <div className="metric-card"><div className="metric-top"><span>{label}</span>{icon}</div><strong>{value}</strong><small>{sub}</small></div>}
