"use client";
import {useEffect,useState} from "react";
import {Save,ShieldCheck,CheckCircle2} from "lucide-react";
import {api} from "../../../../lib/api";
import {useApp} from "../../../AppProvider";
import type {ScreenId} from "../../types";
export const SettingsAI:React.FC<{onNavigate?:(s:ScreenId)=>void}>=()=>{
 const {setTheme}=useApp();
 const [s,setS]=useState<any>({ai_provider:"puter",ai_model:"openai/gpt-oss-20b",language:"English",notifications:true,appearance:"dark",privacy:true});
 const [providers,setProviders]=useState<any[]>([]),[msg,setMsg]=useState(""),[models,setModels]=useState<any[]>([]);
 useEffect(()=>{Promise.all([api<any>("/api/v1/settings"),api<any>("/api/v1/ai/providers")]).then(([settings,providerData])=>{const next={...settings,ai_provider:settings.ai_provider||"puter",ai_model:settings.ai_model||"openai/gpt-oss-20b",appearance:settings.appearance||"dark"};setS(next);setProviders(providerData.providers||[])}).catch(()=>{})},[]);
 useEffect(()=>{api<any>(`/api/v1/ai/models?provider=${encodeURIComponent(s.ai_provider||"puter")}`).then(r=>setModels(r.models||[])).catch(()=>setModels([]))},[s.ai_provider]);
 async function save(){setMsg("");try{setTheme(s.appearance==="dark"?"dark":"light");await api("/api/v1/settings",{method:"POST",body:JSON.stringify(s)});setMsg("Settings saved.")}catch(e:any){setMsg(e.message||"Unable to save settings.")}}
 return <div className="page space-y-6"><div className="page-head"><div><div className="eyebrow">Settings</div><h1>Control your workspace, AI and privacy.</h1><p>Dark theme is the primary workspace. Puter AI is primary for AI interactions; Ollama is the secondary local provider.</p></div><button className="button primary" onClick={save}><Save size={15}/> Save settings</button></div><section className="panel"><div className="panel-head"><div><div className="eyebrow">AI providers</div><h2>Primary → secondary routing</h2></div><ShieldCheck/></div><div className="grid grid-2">{providers.map(x=><button key={x.id} className={`button ${s.ai_provider===x.id?"primary":""}`} style={{justifyContent:"space-between"}} onClick={()=>setS((v:any)=>({...v,ai_provider:x.id,ai_model:x.models?.[0]?.id||x.models?.[0]||v.ai_model}))}><span>{x.name} · {x.id==="puter"?"PRIMARY":"SECONDARY"}</span><span className="tag">{x.connected?"Connected":"Unavailable"}</span></button>)}</div><div className="form-grid" style={{marginTop:15}}><div className="field"><label>AI MODEL</label><select value={s.ai_model||""} onChange={e=>setS((v:any)=>({...v,ai_model:e.target.value}))}>{models.length?models.map((m:any)=><option key={m.id||m} value={m.id||m}>{m.label||m.id||m}</option>):<option value={s.ai_model||""}>{s.ai_model||"No models discovered"}</option>}</select></div><div className="field"><label>LANGUAGE</label><select value={s.language||"English"} onChange={e=>setS((v:any)=>({...v,language:e.target.value}))}><option>English</option><option>Hindi</option><option>Gujarati</option><option>Spanish</option></select></div></div>{msg&&<div className="evaluation"><CheckCircle2 size={15}/> {msg}</div>}</section><section className="panel"><div className="panel-head"><h2>Appearance</h2></div><div className="action-row"><button className={`button ${s.appearance==="dark"?"primary":""}`} onClick={()=>setS((v:any)=>({...v,appearance:"dark"}))}>Dark · Primary</button><button className={`button ${s.appearance==="light"?"primary":""}`} onClick={()=>setS((v:any)=>({...v,appearance:"light"}))}>Light · Secondary</button></div><p className="muted" style={{marginTop:12}}>Light mode uses high-contrast surfaces and text tokens; dark mode remains the default.</p></section></div>
}
